-- Only the reviewed Phase 2 taxonomy is seeded. No sources/questions/rubrics.
INSERT INTO taxonomy_versions(id,description) VALUES ('junior-se-v1','Frozen Phase 2 junior software engineering taxonomy');
INSERT INTO competencies(taxonomy_version,id,kind,parent_id,parent_kind,display_name,description,sort_order) VALUES
('junior-se-v1','dsa','root',NULL,NULL,'Data Structures & Algorithms','Arrays/maps/stacks/queues, elementary trees, Big-O, searching/sorting; choose a suitable structure',0),
('junior-se-v1','dsa.structures','child','dsa','root','Structures','Arrays/maps/stacks/queues, elementary trees, Big-O, searching/sorting; choose a suitable structure',1),
('junior-se-v1','dsa.complexity','child','dsa','root','Complexity','Arrays/maps/stacks/queues, elementary trees, Big-O, searching/sorting; choose a suitable structure',2),
('junior-se-v1','dsa.search-sort','child','dsa','root','Search Sort','Arrays/maps/stacks/queues, elementary trees, Big-O, searching/sorting; choose a suitable structure',3),
('junior-se-v1','oop','root',NULL,NULL,'Object-Oriented Programming','Interfaces/classes, state hiding, substitution, inheritance vs composition; basic maintainable decomposition',4),
('junior-se-v1','oop.encapsulation','child','oop','root','Encapsulation','Interfaces/classes, state hiding, substitution, inheritance vs composition; basic maintainable decomposition',5),
('junior-se-v1','oop.polymorphism','child','oop','root','Polymorphism','Interfaces/classes, state hiding, substitution, inheritance vs composition; basic maintainable decomposition',6),
('junior-se-v1','oop.composition','child','oop','root','Composition','Interfaces/classes, state hiding, substitution, inheritance vs composition; basic maintainable decomposition',7),
('junior-se-v1','dbms-sql','root',NULL,NULL,'DBMS / SQL','SELECT/joins/grouping/NULL, keys/normalization, transaction atomicity, basic isolation and index costs',8),
('junior-se-v1','dbms-sql.queries','child','dbms-sql','root','Queries','SELECT/joins/grouping/NULL, keys/normalization, transaction atomicity, basic isolation and index costs',9),
('junior-se-v1','dbms-sql.modeling','child','dbms-sql','root','Modeling','SELECT/joins/grouping/NULL, keys/normalization, transaction atomicity, basic isolation and index costs',10),
('junior-se-v1','dbms-sql.transactions-indexes','child','dbms-sql','root','Transactions Indexes','SELECT/joins/grouping/NULL, keys/normalization, transaction atomicity, basic isolation and index costs',11),
('junior-se-v1','os','root',NULL,NULL,'Operating Systems','Processes vs threads, stack/heap/virtual memory, races/locks/deadlocks; no kernel implementation',12),
('junior-se-v1','os.process-thread','child','os','root','Process Thread','Processes vs threads, stack/heap/virtual memory, races/locks/deadlocks; no kernel implementation',13),
('junior-se-v1','os.memory','child','os','root','Memory','Processes vs threads, stack/heap/virtual memory, races/locks/deadlocks; no kernel implementation',14),
('junior-se-v1','os.synchronization','child','os','root','Synchronization','Processes vs threads, stack/heap/virtual memory, races/locks/deadlocks; no kernel implementation',15),
('junior-se-v1','networks','root',NULL,NULL,'Computer Networks','TCP/UDP purpose, DNS lookup, HTTP lifecycle/status, HTTPS trust basics; no cryptographic proofs',16),
('junior-se-v1','networks.transport','child','networks','root','Transport','TCP/UDP purpose, DNS lookup, HTTP lifecycle/status, HTTPS trust basics; no cryptographic proofs',17),
('junior-se-v1','networks.http-dns','child','networks','root','Http Dns','TCP/UDP purpose, DNS lookup, HTTP lifecycle/status, HTTPS trust basics; no cryptographic proofs',18),
('junior-se-v1','networks.tls-basics','child','networks','root','Tls Basics','TCP/UDP purpose, DNS lookup, HTTP lifecycle/status, HTTPS trust basics; no cryptographic proofs',19),
('junior-se-v1','backend-web','root',NULL,NULL,'Backend / Web Fundamentals','REST contracts, validation, authentication vs authorization, pagination, transactions, caches and background jobs',20),
('junior-se-v1','backend-web.api-contracts','child','backend-web','root','Api Contracts','REST contracts, validation, authentication vs authorization, pagination, transactions, caches and background jobs',21),
('junior-se-v1','backend-web.auth-validation','child','backend-web','root','Auth Validation','REST contracts, validation, authentication vs authorization, pagination, transactions, caches and background jobs',22),
('junior-se-v1','backend-web.persistence-jobs','child','backend-web','root','Persistence Jobs','REST contracts, validation, authentication vs authorization, pagination, transactions, caches and background jobs',23),
('junior-se-v1','design-lite','root',NULL,NULL,'Basic System Design','Clarify a small product, draw client/API/store, choose data relationships, explain one bottleneck/failure',24),
('junior-se-v1','design-lite.requirements','child','design-lite','root','Requirements','Clarify a small product, draw client/API/store, choose data relationships, explain one bottleneck/failure',25),
('junior-se-v1','design-lite.service-data','child','design-lite','root','Service Data','Clarify a small product, draw client/API/store, choose data relationships, explain one bottleneck/failure',26),
('junior-se-v1','design-lite.reliability','child','design-lite','root','Reliability','Clarify a small product, draw client/API/store, choose data relationships, explain one bottleneck/failure',27),
('junior-se-v1','programming','root',NULL,NULL,'Programming / Coding','Functions/collections/control flow, readable decomposition, tests, exceptions/async basics in chosen language',28),
('junior-se-v1','programming.control-data','child','programming','root','Control Data','Functions/collections/control flow, readable decomposition, tests, exceptions/async basics in chosen language',29),
('junior-se-v1','programming.debug-test','child','programming','root','Debug Test','Functions/collections/control flow, readable decomposition, tests, exceptions/async basics in chosen language',30),
('junior-se-v1','programming.error-handling','child','programming','root','Error Handling','Functions/collections/control flow, readable decomposition, tests, exceptions/async basics in chosen language',31);
