export const SUPPORTED_LANGUAGES = [
    { label: 'JavaScript', value: 'javascript' },
    { label: 'TypeScript', value: 'typescript' },
    { label: 'Python', value: 'python' },
    { label: 'Java', value: 'java' },
    { label: 'C++', value: 'cpp' },
    { label: 'C', value: 'c' },
    { label: 'C#', value: 'csharp' },
    { label: 'Go', value: 'go' },
    { label: 'Rust', value: 'rust' },
    { label: 'PHP', value: 'php' },
    { label: 'Ruby', value: 'ruby' },
    { label: 'Swift', value: 'swift' },
    { label: 'Kotlin', value: 'kotlin' },
    { label: 'Scala', value: 'scala' },
    { label: 'Haskell', value: 'haskell' },
    { label: 'Elixir', value: 'elixir' },
    { label: 'Clojure', value: 'clojure' },
    { label: 'F#', value: 'fsharp' },
    { label: 'R', value: 'r' },
    { label: 'SQL', value: 'sql' },
    { label: 'HTML', value: 'html' },
    { label: 'CSS', value: 'css' },
    { label: 'Solidity', value: 'solidity' },
    { label: 'YAML', value: 'yaml' },
    { label: 'Markdown', value: 'markdown' },
    { label: 'Plain Text', value: 'plaintext' },
    { label: 'Shell', value: 'shell' },
    { label: 'Bash', value: 'bash' },
    { label: 'PowerShell', value: 'powershell' },
    { label: 'Perl', value: 'perl' },
    { label: 'Lua', value: 'lua' },
    { label: 'Dart', value: 'dart' },
    { label: 'Julia', value: 'julia' },
    { label: 'Objective-C', value: 'objective-c' }
];

export const ROLE_LANGUAGE_MAP: Record<string, string> = {
    "Software Engineer": "javascript",
    "Data Scientist": "python",
    "Product Manager": "markdown",
    "UI/UX Designer": "css",
    "Project Manager": "markdown",
    "Business Analyst": "sql",
    "QA Engineer": "javascript",
    "DevOps Engineer": "shell",
    "Cloud Engineer": "yaml",
    "Cyber Security Engineer": "python",
    "Mobile Developer": "swift",
    "Frontend Developer": "javascript",
    "Backend Developer": "python",
    "Full Stack Developer": "javascript",
    "Full Stack Python Developer": "python",
    "Full Stack Java Developer": "java",
    "Machine Learning Engineer": "python",
    "Data Analyst": "python",
    "Machine Learning Developer": "python",
    "MERN Stack Developer": "javascript",
    "MEAN Stack Developer": "typescript",
    "Android Developer": "kotlin",
    "iOS Developer": "swift",
    "Game Developer": "cpp",
    "Embedded Systems Engineer": "c",
    "Blockchain Developer": "solidity",
    "Systems Programmer": "rust",
    "Database Administrator": "sql",
    "Web Developer": "javascript"
};

export const ROLES = [
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "UI/UX Designer",
    "Project Manager",
    "Business Analyst",
    "QA Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Cyber Security Engineer",
    "Mobile Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Full Stack Python Developer",
    "Full Stack Java Developer",
    "Machine Learning Engineer",
    "Data Analyst",
    "Machine Learning Developer",
    "MERN Stack Developer",
    "MEAN Stack Developer",
    "Android Developer",
    "iOS Developer",
    "Game Developer",
    "Embedded Systems Engineer",
    "Blockchain Developer",
    "Systems Programmer",
    "Database Administrator",
    "Web Developer"
];

export const LEVELS = ["Junior", "Mid-level", "Senior", "Architect", "Manager"];

export const TYPES = [{ label: "Oral only", value: "oral-only" }, { label: "Coding mix", value: "coding-mix" }];

export const COUNTS = [5, 10, 15, 20];
