import { useCallback, useEffect, useMemo, useState } from "react";
import apiClient from "../services/apiClient";

type AIReviewPacket = {contractVersion:string;relevance:string;verdict:string;taxonomy:string;category:string;difficulty:string;duplicateWarning:boolean;wordingIssues:string[];correctedQuestion:string|null;technicalCorrectness:string;expectedConcepts:string[];evidenceStatus:string;evidenceSummary:string;rubricGuidance:string[];confidence:string;flags:string[];referenceStatus?:string;eligibleReferenceCount?:number;taxonomyRoot?:string|null};
type SavedAIReview = {id:string;version:number;hash:string;createdAt:string;packet:AIReviewPacket};
type Candidate = {candidate_id:string;state:string;content_hash:string;question_version_id?:string|null;specification:Record<string,unknown>;source_name:string;source_type:string;permission_status:string;review_status:string;company_label:string|null;role:string|null;occurred_on:string|null;round_type:string|null;topics:string[];normalized_text:string;duplicate_links:{candidateId:string;kind:string;similarity:number;duplicateGroup?:string}[];derivation_type:string;confidence:number|null;extraction_metadata:Record<string,unknown>;ai_review:SavedAIReview|null};
type Reference = {chunk_id:string;text:string;source_title:string;origin:string;license_id:string|null;version:number;document_version_id:string};
type ScoringPacket = {questionVersionId:string;concepts:{key:string;label:string;description:string;importance:number;required:boolean;sourceIds:string[]}[];evidenceIndicators?:{conceptKey:string;supportedEvidence:string[];missingEvidence:string[];sourceIds:string[]}[];misconceptions?:{conceptKey:string;description:string;sourceIds:string[]}[];dimensionGuidance?:{dimension:string;guidance:string;sourceIds:string[]}[];followUpConcepts?:{key:string;label:string;description:string;sourceIds:string[]}[];codingObjectiveEvidence?:{objective:string;successEvidence:string[];sourceIds:string[]}|null};
type ScoringItem = {question_version_id:string;question_text:string;content_hash:string;candidate_id?:string;ai_review?:SavedAIReview|null;publication_class:string;technical_references:{chunkId:string;state:string;hash:string;text:string;sourceTitle:string;sourceId:string;licenseId:string|null;permissionHash:string;documentVersionId:string;version:number;chunkHash:string;startOffset:number;endOffset:number}[];drafts:{id:string;hash:string;content:ScoringPacket}[];rubric_kind:string|null;rubric_hash:string|null;rubric_content:ScoringPacket|null};
type Submission = {id:string;state:string;content_hash:string;candidate_count:number;company_label:string|null;role:string;occurred_on:string|null;round_type:string|null;topics:string[];excerpt:string;ai_processing_consent:boolean};
type Source = {id:string;name:string;source_type:string;base_url:string;terms_url:string;permission_basis:string;permission_evidence:string;permission_expires_at:string|null;attribution:string|null;permission_status:string;review_status:string;state:string;full_text_storage:boolean;derived_facts_storage:boolean;model_processing_allowed:boolean;raw_retention:string;allowed_scope:{allowedHosts:string[];allowedPaths:string[]};collection_interval_minutes:number;last_collection_at:string|null;last_success_at:string|null;next_due_at:string|null;last_failure_category:string|null;last_safe_result?:{status:string;discovered:number;imported:number;quarantined:number;errorCategory:string|null}|null;permission_evidence_hash:string|null;permission_reviewed_hash:string|null;withdrawn_at:string|null};
type Trend = {topic:string;role:string;company:string|null;round:string|null;windowDays:number;distinctRecords:number;independentSources:number;questionFamilies:number;trendLabel:string;metadataConfidence:string};
type Tab="sources"|"collections"|"trends"|"review"|"submissions"|"scoring"|"published"|"seeds";

export default function ContentEditorialConsole(){
  const [tab,setTab]=useState<Tab>("review"),[candidates,setCandidates]=useState<Candidate[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[scoring,setScoring]=useState<ScoringItem[]>([]),[seeds,setSeeds]=useState<ScoringItem[]>([]),[references,setReferences]=useState<Reference[]>([]),[sources,setSources]=useState<Source[]>([]),[trends,setTrends]=useState<Trend[]>([]),[history,setHistory]=useState<Record<string,unknown>[]>([]),[days,setDays]=useState(90),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[appRole,setAppRole]=useState("user"),[loadErrors,setLoadErrors]=useState<string[]>([]);
  const load=useCallback(async()=>{
    const canManageSources=["owner","admin"].includes(appRole);
    const requests=[
      apiClient.get("/admin/me"),apiClient.get("/content-intelligence/review/candidates"),apiClient.get("/content-intelligence/scoring-queue"),
      apiClient.get("/content-intelligence/published"),apiClient.get("/content-intelligence/technical-references"),
      apiClient.get("/content-intelligence/seed-review"),apiClient.get("/content-intelligence/review-queue"),
      canManageSources?apiClient.get("/content-intelligence/sources"):Promise.resolve({data:[]}),
      apiClient.get(`/content-intelligence/trends?days=${days}`),
    ];
    const results=await Promise.allSettled(requests),errors:string[]=[];
    const data=(index:number,label:string)=>{const result=results[index];if(result.status==="fulfilled")return result.value.data;errors.push(`${label} could not be loaded.`);return [];};
    const identity=data(0,"Account role");if(identity.role)setAppRole(identity.role);
    setCandidates(data(1,"Question review"));setScoring(data(2,"Scoring queue"));setPublished(data(3,"Published questions"));setReferences(data(4,"Technical references"));
    setSeeds(data(5,"Seed review"));setSubmissions(data(6,"Submission queue"));setSources(data(7,"Source registry"));setTrends(data(8,"Trends"));setLoadErrors(errors);
  },[appRole,days]);
  const [published,setPublished]=useState<ScoringItem[]>([]);
  useEffect(()=>{void load().catch(()=>setMessage("This console is available only to an enabled human reviewer linked to your account."));},[load]);
  const act=async(work:()=>Promise<unknown>,success:string)=>{setBusy(true);setMessage("");try{await work();await load();setMessage(success);}catch(error){const status=(error as {response?:{data?:{code?:string}}})?.response?.data?.code;setMessage(status==="review-hash-mismatch"||status==="rubric_hash_mismatch"?"The item changed after this review was opened. Reload and review the current hash.":"The review action could not be completed.");}finally{setBusy(false);}};
  const tabs=useMemo(()=>[...(appRole==="owner"||appRole==="admin"?[{id:"sources" as const,label:`Sources (${sources.length})`},{id:"collections" as const,label:"Collection History"}]:[]),{id:"trends" as const,label:"Trends"},{id:"review" as const,label:`Question Review (${candidates.length})`},{id:"submissions" as const,label:`Submission Queue (${submissions.length})`},{id:"scoring" as const,label:"Scoring Queue"},{id:"published" as const,label:"Published Questions"},{id:"seeds" as const,label:`Seed Review (${seeds.length})`}], [appRole,candidates.length,submissions.length,seeds.length,sources.length]);
  return <section className="mx-auto max-w-6xl space-y-6 text-surface-100">
    <header><p className="text-sm uppercase tracking-wider text-cyan-300">Protected editorial tools</p><h1 className="mt-2 text-3xl font-semibold">Interview content review</h1><p className="mt-2 text-surface-300">Role: <span className="capitalize">{appRole}</span>. Human approval is required at each stage. Every review action is bound to the exact content hash.</p></header>
    <nav aria-label="Editorial sections" className="flex flex-wrap gap-2">{tabs.map(item=><button key={item.id} onClick={()=>setTab(item.id)} aria-pressed={tab===item.id} className={`rounded-lg border px-3 py-2 text-sm ${tab===item.id?"border-cyan-300 text-cyan-100":"border-white/15 text-surface-300"}`}>{item.label}</button>)}</nav>
    {message&&<p role="status" className="rounded-lg border border-cyan-300/30 p-3 text-sm">{message}</p>}
    {loadErrors.map(error=><p key={error} role="alert" className="rounded-lg border border-amber-300/30 p-3 text-sm text-amber-100">{error} Other sections remain available.</p>)}
    {tab==="sources"&&<SourceRegistry sources={sources} busy={busy} act={act} onHistory={async id=>{const result=await apiClient.get(`/content-intelligence/sources/${id}/collections`);setHistory(result.data);setTab("collections");}}/>}
    {tab==="collections"&&<div className="space-y-3">{history.length?history.map((row,index)=><pre key={String(row.id||index)} className="overflow-auto rounded border border-white/10 p-3 text-xs">{JSON.stringify(row,null,2)}</pre>):<p className="text-sm text-surface-400">Select a source’s collection history to inspect safe run counts and error categories.</p>}</div>}
    {tab==="trends"&&<div className="space-y-4"><label className="text-sm">Window <select value={days} onChange={event=>setDays(Number(event.target.value))} className="ml-2 rounded bg-slate-800 p-2"><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select></label>{trends.map((trend,index)=><article key={`${trend.topic}-${index}`} className="rounded-xl border border-white/15 p-4"><h2 className="font-semibold">{trend.topic} · {trend.trendLabel}</h2><p className="mt-1 text-sm">{trend.role} · {trend.company||"company not reported"} · {trend.round||"round unknown"}</p><p className="mt-1 text-xs text-surface-400">{trend.distinctRecords} distinct reviewed records · {trend.independentSources} sources · {trend.questionFamilies} question families · {trend.metadataConfidence}</p></article>)}{!trends.length&&<p className="text-sm text-surface-400">No reviewed trend evidence in this window.</p>}</div>}
    {tab==="review"&&<div className="space-y-4">{candidates.map(item=><CandidateCard key={item.candidate_id} item={item} candidates={candidates} busy={busy} act={act}/>)}</div>}
    {tab==="submissions"&&<div className="space-y-4">{submissions.map(item=><article key={item.id} className="space-y-3 rounded-xl border border-white/15 bg-slate-900/60 p-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{item.role||"Role not reported"} · {item.company_label||"company not reported"} · {item.round_type||"round unknown"}</h2><code className="max-w-64 break-all text-xs text-cyan-200">{item.content_hash}</code></div><p className="text-sm">{item.occurred_on||"Date unknown"} · AI processing consent: {item.ai_processing_consent?"granted":"not granted"} · {item.state} · {item.candidate_count} proposals</p><details><summary className="cursor-pointer text-sm text-cyan-200">Quarantined submission excerpt</summary><p className="mt-2 whitespace-pre-wrap rounded bg-slate-950/50 p-3 text-sm">{item.excerpt}</p></details><div className="flex flex-wrap gap-2"><button disabled={busy||item.state!=="review_required"||!item.ai_processing_consent} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/submissions/${item.id}/extract`,{expectedHash:item.content_hash}),item.candidate_count?"Re-extraction requested; proposals remain unapproved.":"AI proposals created for human review.")} className="rounded bg-cyan-800 px-3 py-2 text-sm disabled:opacity-40">{item.candidate_count?"Request Re-extraction":"Request AI extraction"}</button>{item.state==="review_required"&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/records/${item.id}/approve`,{expectedHash:item.content_hash}),"Exact source record approved; question candidates still require separate review.")} className="rounded border border-emerald-300/40 px-3 py-2 text-sm">Approve source record</button>}{item.state==="approved"&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/records/${item.id}/publish`),"Source record published; dependent questions remain independently reviewed.")} className="rounded border border-cyan-300/40 px-3 py-2 text-sm">Publish source record</button>}</div></article>)}</div>}
    {(tab==="scoring"||tab==="published"||tab==="seeds")&&<div className="space-y-4">{(tab==="seeds"?seeds:tab==="published"?published:scoring).map(item=><ScoringCard key={item.question_version_id} item={item} references={references} busy={busy} act={act}/>)}</div>}
  </section>;
}

function AIReviewProposal({review}:{review:SavedAIReview}){const packet=review.packet;return <details className="rounded border border-cyan-300/20 bg-cyan-950/10 p-3 text-sm"><summary className="cursor-pointer text-cyan-200">AI proposal v{review.version} · {packet.verdict} · {packet.confidence} confidence · human decision required</summary><div className="mt-3 space-y-2"><p>Relevance: {packet.relevance} · taxonomy: {packet.taxonomyRoot||"root unknown"} / {packet.taxonomy} · {packet.category} · {packet.difficulty} · technical correctness: {packet.technicalCorrectness}</p><p>Duplicate warning: {packet.duplicateWarning?"possible duplicate":"none suggested"} · evidence: {packet.evidenceStatus} — {packet.evidenceSummary} · technical references: {packet.referenceStatus||"unknown"} ({packet.eligibleReferenceCount??0})</p>{packet.correctedQuestion&&<p><strong>Suggested wording:</strong> {packet.correctedQuestion}</p>}<p><strong>Expected concepts:</strong> {packet.expectedConcepts.join(" · ")}</p>{packet.wordingIssues.length>0&&<p><strong>Wording issues:</strong> {packet.wordingIssues.join(" · ")}</p>}<p><strong>Rubric guidance:</strong> {packet.rubricGuidance.join(" · ")}</p><p><strong>Flags:</strong> {packet.flags.join(" · ")||"none"}</p><p className="break-all text-xs text-surface-400">Packet hash: {review.hash} · {review.createdAt}. This proposal never changes candidate state or approves publication.</p></div></details>}

function CandidateCard({item,candidates,busy,act}:{item:Candidate;candidates:Candidate[];busy:boolean;act:(work:()=>Promise<unknown>,success:string)=>Promise<void>}){
  const [text,setText]=useState(String(item.specification.text||"")),[family,setFamily]=useState(""),[supersedes,setSupersedes]=useState(""),[duplicateDecision,setDuplicateDecision]=useState(item.duplicate_links?.some(link=>link.kind==="exact")?"":"distinct");
  const encoded=encodeURIComponent(item.candidate_id),expectedHash=item.content_hash,reviewable=item.state==="review_required";
  return <article className="space-y-3 rounded-xl border border-white/15 bg-slate-900/60 p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{item.source_name} · {item.source_type} · {item.state}</h2><p className="text-xs text-surface-400">Permission: {item.permission_status}/{item.review_status} · {item.role} · {item.occurred_on||"date unknown"} · {item.round_type||"round unknown"}</p></div><code className="max-w-64 break-all text-xs text-cyan-200">{expectedHash}</code></div>
    <p className="text-sm">Company: {item.company_label||"not reported"} · Derivation: {item.derivation_type} · Extraction confidence: {item.confidence??"not provided"}</p>
    <p className="rounded bg-slate-950/50 p-3 text-sm">{String(item.specification.text||"")}</p>
    <button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/ai-review`,{expectedHash}),item.ai_review?"New AI proposal version saved. Human review is still required.":"AI proposal saved. Human review is still required.")} className="rounded border border-cyan-300/40 px-3 py-2 text-sm">{item.ai_review?"Re-run AI Review":"Request AI Review"}</button>
    {item.ai_review&&<AIReviewProposal review={item.ai_review}/>}
    {typeof item.extraction_metadata?.evidenceText==="string"&&<p className="rounded border border-cyan-300/20 bg-cyan-950/20 p-3 text-sm">Evidence span ({String(item.extraction_metadata.evidenceStart)}–{String(item.extraction_metadata.evidenceEnd)}): “{item.extraction_metadata.evidenceText}” · {String(item.extraction_metadata.language||"language unknown")}</p>}
    <details><summary className="cursor-pointer text-sm text-cyan-200">Permitted evidence excerpt</summary><p className="mt-2 whitespace-pre-wrap rounded bg-slate-950/50 p-3 text-sm">{item.normalized_text}</p></details>
    {item.duplicate_links?.length>0&&<p className="text-sm text-amber-200">Possible duplicates: {item.duplicate_links.map(v=>`${v.candidateId} (${v.kind}, ${v.similarity})`).join(" · ")}</p>}
    <label className="block text-sm">Edit question<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={12000} rows={3} className="mt-1 w-full rounded bg-slate-800 p-3"/></label>
    <div className="flex flex-wrap gap-2">
      {item.duplicate_links?.length>0&&<select aria-label="Duplicate review decision" value={duplicateDecision} onChange={e=>setDuplicateDecision(e.target.value)} className="rounded bg-slate-800 px-2 text-sm"><option value="">Resolve exact duplicate first</option><option value="distinct">Keep distinct</option><option value="retain-provenance">Retain exact duplicate provenance</option></select>}
      <button disabled={busy||!reviewable||(Boolean(item.duplicate_links?.length)&&!duplicateDecision)} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/approve`,{expectedHash,duplicateDecision:duplicateDecision||undefined}),"Question approved.")} className="rounded bg-emerald-700 px-3 py-2 text-sm">Approve</button>
      <button disabled={busy||!reviewable||!text.trim()} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/edit-approve`,{expectedHash,specification:{...item.specification,text},derivation:"paraphrased"}),"Edited question approved.")} className="rounded bg-cyan-800 px-3 py-2 text-sm">Edit + Approve</button>
      <button disabled={busy||!reviewable} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/reject`,{expectedHash,reason:"reviewer-rejected"}),"Question rejected.")} className="rounded bg-rose-900 px-3 py-2 text-sm">Reject</button>
      <select value={family} onChange={e=>setFamily(e.target.value)} aria-label="Duplicate question family" className="rounded bg-slate-800 px-2 text-sm"><option value="">Choose approved duplicate</option>{candidates.filter(c=>c.candidate_id!==item.candidate_id&&["approved","published"].includes(c.state)).map(c=><option key={c.candidate_id} value={c.candidate_id}>{String(c.specification.text||c.candidate_id)}</option>)}</select>
      <button disabled={busy||!reviewable||!family} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/duplicate`,{expectedHash,duplicateOf:family,reason:"duplicate-family"}),"Duplicate link recorded.")} className="rounded border border-amber-400/50 px-3 py-2 text-sm">Mark Duplicate</button>
      <button disabled={busy||!family} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/family`,{expectedHash,relatedId:family}),"Question family linked for reviewer context.")} className="rounded border border-amber-300/40 px-3 py-2 text-sm">Link Family</button>
      <select value={supersedes} onChange={e=>setSupersedes(e.target.value)} aria-label="Question this supersedes" className="max-w-xl rounded bg-slate-800 px-2 text-sm"><option value="">Choose published question to supersede</option>{candidates.filter(c=>c.candidate_id!==item.candidate_id&&c.state==="published").map(c=><option key={c.candidate_id} value={c.candidate_id}>{String(c.specification.text||c.candidate_id)}</option>)}</select>
      <button disabled={busy||!supersedes||item.state!=="published"} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/supersede`,{expectedHash,supersedesId:supersedes}),"Published question superseded; existing session snapshots remain readable.")} className="rounded border border-cyan-300/40 px-3 py-2 text-sm">Supersede Selected</button>
      <button disabled={busy||!reviewable} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/withdraw`,{expectedHash,reason:"reviewer-withdrawn"}),"Question withdrawn.")} className="rounded border border-white/20 px-3 py-2 text-sm">Withdraw</button>
      {item.state==="approved"&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/publish`,{expectedHash}),"Question published; retrieval indexing was attempted.")} className="rounded bg-cyan-700 px-3 py-2 text-sm">Publish and index</button>}
    </div>
  </article>;
}

function ScoringCard({item,references,busy,act}:{item:ScoringItem;references:Reference[];busy:boolean;act:(work:()=>Promise<unknown>,success:string)=>Promise<void>}){
  const [chunkId,setChunkId]=useState(""),[edits,setEdits]=useState<Record<string,string>>({});
  return <article className="space-y-3 rounded-xl border border-white/15 bg-slate-900/60 p-4">
    <div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{item.question_text}</h2><span className="text-sm text-cyan-200">{item.publication_class}</span></div>
    <p className="text-xs text-surface-400">Question hash: {item.content_hash}</p>
    {item.candidate_id&&<><button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${item.candidate_id}/ai-review`,{expectedHash:item.content_hash}),"AI proposal saved as a new version. Human review remains required.")} className="rounded border border-cyan-300/40 px-3 py-2 text-sm">{item.ai_review?"Re-run AI Review":"Request AI Review"}</button>{item.ai_review&&<AIReviewProposal review={item.ai_review}/>}</>}
    <p className="text-sm">Reviewed references: {item.technical_references?.filter(ref=>ref.state==="approved").length||0} · Current rubric: {item.rubric_kind||"none"}</p>
    {item.technical_references?.filter(ref=>ref.state==="approved").map(ref=><details key={ref.chunkId} className="rounded border border-white/10 p-3"><summary className="cursor-pointer text-sm">{ref.sourceTitle} · v{ref.version} · {ref.hash}</summary><p className="mt-2 text-xs text-surface-400">Source {ref.sourceId} · document {ref.documentVersionId} · chunk {ref.chunkId} · offsets {ref.startOffset}–{ref.endOffset} · chunk hash {ref.chunkHash} · license {ref.licenseId||"not specified"} · permission evidence {ref.permissionHash}</p><p className="mt-2 whitespace-pre-wrap text-sm text-surface-300">{ref.text}</p><button disabled={busy} onClick={()=>void act(()=>apiClient.delete(`/content-intelligence/scoring/${item.question_version_id}/references/${ref.chunkId}`),"Reference removed from future scoring eligibility.")} className="mt-2 text-sm text-rose-300 underline">Remove reference</button></details>)}
    {item.rubric_content&&<div className="rounded border border-white/10 p-3"><p className="text-xs text-surface-400">Approved packet {item.rubric_hash}</p><ul className="mt-2 list-disc pl-5 text-sm">{item.rubric_content.concepts.map(concept=><li key={concept.key}>{concept.label} · weight {concept.importance} · {concept.required?"required":"supporting"} — {concept.description}</li>)}</ul></div>}
    {item.rubric_content&&<Guidance packet={item.rubric_content}/>}
    <div className="flex flex-wrap gap-2"><select value={chunkId} onChange={e=>setChunkId(e.target.value)} aria-label="Technical reference" className="max-w-xl rounded bg-slate-800 px-3 py-2 text-sm"><option value="">Select permitted technical reference</option>{references.map(ref=><option key={ref.chunk_id} value={ref.chunk_id}>{ref.source_title} · {ref.license_id||"license unspecified"} · v{ref.version}</option>)}</select>
      <button disabled={busy||!chunkId} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/${item.question_version_id}/references`,{chunkId}),"Technical reference attached and approved.")} className="rounded border border-white/20 px-3 py-2 text-sm">Add reference</button>
      <button disabled={busy||!(item.technical_references?.some(ref=>ref.state==="approved"))} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/${item.question_version_id}/draft`),"A new scoring packet draft was created.")} className="rounded bg-cyan-800 px-3 py-2 text-sm">{item.drafts?.length?"Regenerate packet":"Draft concepts and rubric"}</button>
      {item.rubric_hash&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/${item.question_version_id}/withdraw`,{expectedHash:item.rubric_hash}),"Scoring packet withdrawn from future use.")} className="rounded border border-rose-400/40 px-3 py-2 text-sm">Withdraw packet</button>}</div>
    {(item.drafts||[]).map(draft=><div key={draft.id} className="rounded border border-white/10 p-3"><p className="text-xs">Packet hash: <code className="break-all">{draft.hash}</code></p><ul className="my-2 list-disc pl-5 text-sm">{draft.content.concepts.map(c=><li key={c.key}>{c.label} — {c.description}</li>)}</ul><Guidance packet={draft.content}/>
      <label className="block text-xs text-surface-400">Edit packet JSON<textarea aria-label={`Edit scoring packet ${draft.id}`} value={edits[draft.id]??JSON.stringify(draft.content,null,2)} onChange={e=>setEdits(current=>({...current,[draft.id]:e.target.value}))} rows={8} className="mt-1 w-full rounded bg-slate-950 p-2 font-mono text-xs"/></label>
      <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>{try{const content=JSON.parse(edits[draft.id]??JSON.stringify(draft.content));void act(()=>apiClient.post(`/content-intelligence/scoring/drafts/${draft.id}/edit`,{expectedHash:draft.hash,content}),"Edited packet saved as a new immutable draft.");}catch{setEdits(current=>({...current,[draft.id]:current[draft.id]||""}));}}} className="rounded border border-white/20 px-3 py-2 text-sm">Save edited draft</button><button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/drafts/${draft.id}/approve`,{expectedHash:draft.hash}),"Exact scoring packet approved.")} className="rounded bg-emerald-700 px-3 py-2 text-sm">Approve scoring packet</button><button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/drafts/${draft.id}/reject`,{expectedHash:draft.hash,reason:"scoring-rejected"}),"Scoring packet rejected.")} className="rounded bg-rose-900 px-3 py-2 text-sm">Reject packet</button></div>
    </div>)}
  </article>;
}

function Guidance({packet}:{packet:ScoringPacket}){return <details className="rounded border border-white/10 p-3 text-sm"><summary className="cursor-pointer text-cyan-200">Evidence and learning guidance</summary><div className="mt-3 space-y-2">
  {(packet.evidenceIndicators||[]).map((item,index)=><p key={`e${index}`}><strong>{item.conceptKey} evidence:</strong> Supported: {item.supportedEvidence.join("; ")||"none specified"}. Gaps: {item.missingEvidence.join("; ")||"none specified"}.</p>)}
  {(packet.misconceptions||[]).map((item,index)=><p key={`m${index}`}><strong>{item.conceptKey} misconception:</strong> {item.description}</p>)}
  {(packet.dimensionGuidance||[]).map((item,index)=><p key={`d${index}`}><strong>{item.dimension}:</strong> {item.guidance}</p>)}
  {(packet.followUpConcepts||[]).map(item=><p key={`f${item.key}`}><strong>Follow-up {item.label}:</strong> {item.description}</p>)}
  {packet.codingObjectiveEvidence&&<p><strong>Coding objective:</strong> {packet.codingObjectiveEvidence.objective} Evidence: {packet.codingObjectiveEvidence.successEvidence.join("; ")}.</p>}
  {!packet.evidenceIndicators?.length&&!packet.misconceptions?.length&&!packet.dimensionGuidance?.length&&!packet.followUpConcepts?.length&&!packet.codingObjectiveEvidence&&<p className="text-surface-400">No additional editorial guidance is attached.</p>}
</div></details>}

function SourceRegistry({sources,busy,act,onHistory}:{sources:Source[];busy:boolean;act:(work:()=>Promise<unknown>,success:string)=>Promise<void>;onHistory:(id:string)=>Promise<void>}){
  const [now,setNow]=useState<number|null>(null);
  useEffect(()=>{const refresh=()=>setNow(Date.now());refresh();const timer=window.setInterval(refresh,60_000);return()=>window.clearInterval(timer);},[]);
  const [name,setName]=useState(""),[type,setType]=useState("rss_atom"),[baseUrl,setBaseUrl]=useState(""),[termsUrl,setTermsUrl]=useState(""),[basis,setBasis]=useState(""),[evidence,setEvidence]=useState(""),[permissionExpiry,setPermissionExpiry]=useState(""),[attribution,setAttribution]=useState(""),[interval,setInterval]=useState(1440),[retention,setRetention]=useState(7),[fullText,setFullText]=useState(false),[derived,setDerived]=useState(true),[modelProcessing,setModelProcessing]=useState(false),[hosts,setHosts]=useState(""),[paths,setPaths]=useState(""),[editingId,setEditingId]=useState<string|null>(null);
  const edit=(source:Source)=>{setEditingId(source.id);setName(source.name);setType(source.source_type);setBaseUrl(source.base_url);setTermsUrl(source.terms_url);setBasis(source.permission_basis);setEvidence(source.permission_evidence);setPermissionExpiry(source.permission_expires_at?new Date(new Date(source.permission_expires_at).getTime()-new Date(source.permission_expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):"");setAttribution(source.attribution||"");setInterval(source.collection_interval_minutes);setRetention(Number.parseInt(source.raw_retention,10)||0);setFullText(source.full_text_storage);setDerived(source.derived_facts_storage);setModelProcessing(source.model_processing_allowed);setHosts(source.allowed_scope.allowedHosts.join(","));setPaths(source.allowed_scope.allowedPaths.join(","));};
  const create=()=>{let host="",path="/";try{const url=new URL(baseUrl);host=url.hostname;path=url.pathname;}catch{/* API returns a safe validation error. */}const value={name,sourceType:type,baseUrl,termsUrl,permissionBasis:basis,permissionEvidence:evidence,permissionExpiresAt:permissionExpiry?new Date(permissionExpiry).toISOString():null,attribution,intervalMinutes:interval,rawRetentionDays:retention,fullTextStorage:fullText,derivedDataStorage:derived,modelProcessingAllowed:modelProcessing,allowedHosts:hosts.split(",").map(x=>x.trim()).filter(Boolean).length?hosts.split(",").map(x=>x.trim()):[host],allowedPaths:paths.split(",").map(x=>x.trim()).filter(Boolean).length?paths.split(",").map(x=>x.trim()).filter(Boolean):[path]};return act(()=>editingId?apiClient.patch(`/content-intelligence/sources/${editingId}`,value):apiClient.post("/content-intelligence/sources",value),editingId?"Source updated. Permission-relevant changes require a new human review and leave the source disabled.":"Source created disabled. A linked human must review the exact permission evidence before enabling collection.");};
  return <div className="space-y-5"><p className="rounded border border-cyan-300/20 p-3 text-sm text-surface-300">The backend does not search the internet automatically. Only configured, permission-reviewed, enabled sources are collected. Sources (0) means no external collection. Scheduled collection runs only while the backend worker runtime is running.</p><form onSubmit={event=>{event.preventDefault();void create();}} className="grid gap-3 rounded-xl border border-white/15 p-4 md:grid-cols-2">
    <h2 className="md:col-span-2 font-semibold">{editingId?"Edit source configuration":"Register a source (starts disabled)"}</h2>
    <label className="text-sm">Display name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Source adapter<select value={type} onChange={e=>setType(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"><option value="rss_atom">RSS / Atom</option><option value="official_api">REST / JSON API</option></select></label>
    <label className="text-sm">Feed/API URL<input required type="url" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Terms URL<input required type="url" value={termsUrl} onChange={e=>setTermsUrl(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Permission basis<input required value={basis} onChange={e=>setBasis(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Permission evidence<textarea required value={evidence} onChange={e=>setEvidence(e.target.value)} rows={2} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Permission expires (optional)<input type="datetime-local" value={permissionExpiry} onChange={e=>setPermissionExpiry(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/><span className="mt-1 block text-xs text-surface-400">Expired permission disables future collection and removes linked content from new planner/trend results. Updating expiry requires a fresh exact-hash review.</span></label>
    <label className="text-sm">Allowed hosts (comma-separated)<input value={hosts} onChange={e=>setHosts(e.target.value)} placeholder="derived from URL when blank" className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Allowed paths<input value={paths} onChange={e=>setPaths(e.target.value)} placeholder="feed path used when blank" className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Collection interval (minutes)<input type="number" min={60} max={10080} value={interval} onChange={e=>setInterval(Number(e.target.value))} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Raw content retention (days)<input type="number" min={0} max={30} value={retention} onChange={e=>setRetention(Number(e.target.value))} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Attribution requirements<input value={attribution} onChange={e=>setAttribution(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={fullText} onChange={e=>setFullText(e.target.checked)}/>Permission allows full text storage</label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={derived} onChange={e=>setDerived(e.target.checked)}/>Permission allows derived metadata storage</label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={modelProcessing} onChange={e=>setModelProcessing(e.target.checked)}/>Written permission allows model processing</label>
    <button disabled={busy} className="rounded bg-cyan-800 px-3 py-2 text-sm disabled:opacity-40">{editingId?"Save source configuration":"Create disabled source"}</button>{editingId&&<button type="button" onClick={()=>setEditingId(null)} className="rounded border border-white/20 px-3 py-2 text-sm">Cancel edit</button>}
  </form><div className="space-y-3">{sources.map(source=><article key={source.id} className="space-y-3 rounded-xl border border-white/15 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{source.name}</h2><span className="text-sm">{source.source_type} · {source.permission_status}/{source.review_status} · {source.state}</span></div><p className="break-all text-xs text-surface-400">{source.base_url} · every {source.collection_interval_minutes} minutes · next {source.next_due_at||"not scheduled"}</p><p className={`text-xs ${source.permission_expires_at&&Date.parse(source.permission_expires_at)<=(now??0)?"text-rose-300":"text-surface-400"}`}>Permission {source.permission_expires_at?`expires ${source.permission_expires_at}${Date.parse(source.permission_expires_at)<=(now??0)?" (expired)":""}`:"has no recorded expiry"}</p><p className="text-xs text-surface-400">Last run {source.last_collection_at||"never"} · last success {source.last_success_at||"never"} · failure {source.last_failure_category||"none"}</p><p className="text-xs">Last safe result: {source.last_safe_result?`${source.last_safe_result.status} · ${source.last_safe_result.discovered} discovered / ${source.last_safe_result.imported} imported / ${source.last_safe_result.quarantined} quarantined${source.last_safe_result.errorCategory?` · ${source.last_safe_result.errorCategory}`:""}`:"no collection result"}</p><p className="text-xs">Storage: full text {source.full_text_storage?"permitted":"blocked"} · derived data {source.derived_facts_storage?"permitted":"blocked"} · model processing {source.model_processing_allowed?"permitted":"blocked"} · retention {source.raw_retention}</p><p className="break-all text-xs">Permission basis: {source.permission_basis}. Evidence: {source.permission_evidence}</p><p className="break-all text-xs">Permission evidence hash: {source.permission_evidence_hash||"unavailable"}</p><div className="flex flex-wrap gap-2">
    {source.permission_evidence_hash&&source.permission_reviewed_hash!==source.permission_evidence_hash&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/permission-review`,{expectedHash:source.permission_evidence_hash}),"Permission review recorded for this exact evidence hash.")} className="rounded border border-amber-300/40 px-3 py-2 text-sm">Record permission review</button>}
    {source.state!=="enabled"&&<button disabled={busy||!!source.withdrawn_at||source.permission_reviewed_hash!==source.permission_evidence_hash} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/enable`),"Source enabled.")} className="rounded border border-emerald-300/40 px-3 py-2 text-sm disabled:opacity-40">Enable</button>}
    {source.state==="enabled"&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/disable`),"Source disabled.")} className="rounded border border-white/20 px-3 py-2 text-sm">Disable</button>}
    <button disabled={busy||source.state!=="enabled"||!source.full_text_storage} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/collect`),"Collection queued through the durable operation runtime.")} className="rounded bg-cyan-900 px-3 py-2 text-sm disabled:opacity-40">Collect now</button>
    <button disabled={busy||!!source.withdrawn_at} onClick={()=>edit(source)} className="rounded border border-white/20 px-3 py-2 text-sm disabled:opacity-40">Edit source</button>
    <button disabled={busy} onClick={()=>void onHistory(source.id)} className="rounded border border-white/20 px-3 py-2 text-sm">Collection history</button>
    {!source.withdrawn_at&&<button disabled={busy} onClick={()=>{const reason=window.prompt("Withdrawal reason");if(reason?.trim())void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/withdraw`,{reason}),"Source withdrawn and current content removed from future eligibility.");}} className="rounded border border-rose-300/40 px-3 py-2 text-sm">Withdraw</button>}
  </div></article>)}{!sources.length&&<p className="text-sm text-surface-400">No sources are registered.</p>}</div></div>;
}
