import { useCallback, useEffect, useMemo, useState, useSyncExternalStore } from "react";
import type { FormEvent } from "react";
import { useSelector } from "react-redux";
import type { RootState } from "../app/store";
import { SourceRowErrorBoundary } from "../components/EditorialErrorBoundary";
import apiClient from "../services/apiClient";
import { editorialQueryCache } from "../services/editorialQueryCache";

type AIReviewPacket = {contractVersion:string;relevance:string;verdict:string;taxonomy:string;category:string;difficulty:string;duplicateWarning:boolean;wordingIssues:string[];correctedQuestion:string|null;technicalCorrectness:string;expectedConcepts:string[];evidenceStatus:string;evidenceSummary:string;rubricGuidance:string[];confidence:string;flags:string[];referenceStatus?:string;eligibleReferenceCount?:number;taxonomyRoot?:string|null};
type SavedAIReview = {id:string;version:number;hash:string;createdAt:string;packet:AIReviewPacket};
type Candidate = {candidate_id:string;state:string;content_hash:string;question_version_id?:string|null;specification:Record<string,unknown>;source_name:string;source_type:string;permission_status:string;review_status:string;company_label:string|null;role:string|null;occurred_on:string|null;round_type:string|null;topics:string[];normalized_text:string;duplicate_links:{candidateId:string;kind:string;similarity:number;duplicateGroup?:string}[];derivation_type:string;confidence:number|null;extraction_metadata:Record<string,unknown>;ai_review:SavedAIReview|null;ai_processing_consent?:boolean;model_processing_allowed?:boolean};
type Reference = {chunk_id:string;text:string;source_title:string;origin:string;license_id:string|null;version:number;document_version_id:string};
type ManualReference = {record_id:string;input_hash:string;content_hash:string;title:string;normalized_text:string;source_name:string};
type ScoringPacket = {questionVersionId:string;concepts:{key:string;label:string;description:string;importance:number;required:boolean;sourceIds:string[]}[];evidenceIndicators?:{conceptKey:string;supportedEvidence:string[];missingEvidence:string[];sourceIds:string[]}[];misconceptions?:{conceptKey:string;description:string;sourceIds:string[]}[];dimensionGuidance?:{dimension:string;guidance:string;sourceIds:string[]}[];followUpConcepts?:{key:string;label:string;description:string;sourceIds:string[]}[];codingObjectiveEvidence?:{objective:string;successEvidence:string[];sourceIds:string[]}|null};
type ScoringItem = {question_version_id:string;question_text:string;content_hash:string;candidate_id?:string;is_seed?:boolean;seed_question_approved?:boolean;reviewed_reference_count?:number;scoring_packet_hash?:string|null;ai_review?:SavedAIReview|null;publication_class:string;technical_references:{chunkId:string;state:string;hash:string;text:string;sourceTitle:string;sourceId:string;licenseId:string|null;permissionHash:string;documentVersionId:string;version:number;chunkHash:string;startOffset:number;endOffset:number}[];drafts:{id:string;hash:string;content:ScoringPacket}[];rubric_kind:string|null;rubric_hash:string|null;rubric_content:ScoringPacket|null};
type Submission = {id:string;state:string;content_hash:string;candidate_count:number;company_label:string|null;role:string;occurred_on:string|null;round_type:string|null;topics:string[];excerpt:string;ai_processing_consent:boolean};
type Source = {id:string;name:string;source_type:string;base_url:string;terms_url:string;permission_basis:string;permission_evidence:string;permission_expires_at:string|null;attribution:string|null;permission_status:string;review_status:string;state:string;full_text_storage:boolean;derived_facts_storage:boolean;model_processing_allowed:boolean;raw_retention_seconds:number;allowed_scope:{allowedHosts:string[];allowedPaths:string[]};collection_interval_minutes:number;last_collection_at:string|null;last_success_at:string|null;next_due_at:string|null;last_failure_category:string|null;last_safe_result?:{status:string;discovered:number;imported:number;quarantined:number;errorCategory:string|null}|null;permission_evidence_hash:string|null;permission_reviewed_hash:string|null;withdrawn_at:string|null};
type Trend = {topic:string;role:string;company:string|null;round:string|null;windowDays:number;distinctRecords:number;independentSources:number;questionFamilies:number;trendLabel:string;metadataConfidence:string};
type BankQuestion = {question_version_id:string;question_text:string;category:string;difficulty:string;primary_competency:string;topic:string;inventory_class:"TRUSTED_BASELINE"|"DYNAMIC_REVIEWED";origin:string;display_status:string};
type InterviewBank = {starterQuestions:number;approvedNewQuestions:number;totalAvailable:number;questions:BankQuestion[]};
type Competency = {id:string;label:string;parentId:string};
type Tab="bank"|"sources"|"review";
type EditorialAction=(work:()=>Promise<unknown>,success:string,invalidates?:string[])=>Promise<void>;

export default function ContentEditorialConsole(){
  const roleState=useSelector((state:RootState)=>state.role);
  const cacheVersion=useSyncExternalStore(editorialQueryCache.subscribe,editorialQueryCache.getVersion);
  const appRole=roleState.status==="ready"?roleState.role||"user":"user";
  const apiRoleReady=roleState.status==="ready"&&roleState.reviewerLinked&&["owner","admin","reviewer"].includes(appRole);
  const identity=roleState.userId?`${roleState.userId}:${roleState.status}:${roleState.role||""}:${roleState.reviewerLinked}`:null;
  const [tab,setTab]=useState<Tab>("bank"),[candidates,setCandidates]=useState<Candidate[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[scoring,setScoring]=useState<ScoringItem[]>([]),[references,setReferences]=useState<Reference[]>([]),[manualReferences,setManualReferences]=useState<ManualReference[]>([]),[sources,setSources]=useState<Source[]>([]),[trends,setTrends]=useState<Trend[]>([]),[bank,setBank]=useState<InterviewBank>({starterQuestions:0,approvedNewQuestions:0,totalAvailable:0,questions:[]}),[competencies,setCompetencies]=useState<Competency[]>([]),[history,setHistory]=useState<Record<string,unknown>[]>([]),[historyKey,setHistoryKey]=useState(""),[days,setDays]=useState(90),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[candidateSearch,setCandidateSearch]=useState(""),[candidatePage,setCandidatePage]=useState(0),[manualRecordId,setManualRecordId]=useState<string|undefined>(),[manualQuestionText,setManualQuestionText]=useState("");
  useEffect(()=>{
    editorialQueryCache.setIdentity(identity);
    setCandidates([]);setSubmissions([]);setScoring([]);setReferences([]);setManualReferences([]);setSources([]);setTrends([]);setBank({starterQuestions:0,approvedNewQuestions:0,totalAvailable:0,questions:[]});setCompetencies([]);setHistory([]);
  },[identity]);
  const activePaths=useMemo(()=>{
    switch(tab){
      case "bank":return ["/content-intelligence/interview-bank"];
      case "review":return ["/content-intelligence/review/candidates","/content-intelligence/review-queue","/content-intelligence/scoring-queue","/content-intelligence/technical-references",...(apiRoleReady?["/content-intelligence/review/manual-references","/content-intelligence/review/competencies"]:[])];
      case "sources":return appRole==="owner"||appRole==="admin"?["/content-intelligence/sources"]:[];
    }
  },[apiRoleReady,appRole,tab]);
  const assignCachedData=useCallback(()=>{
    const data=<T,>(key:string):T|undefined=>editorialQueryCache.get<T>(key).data;
    const candidatesData=data<Candidate[]>("/content-intelligence/review/candidates");if(candidatesData)setCandidates(candidatesData);
    const bankData=data<InterviewBank>("/content-intelligence/interview-bank");if(bankData)setBank(bankData);
    const competenciesData=data<Competency[]>("/content-intelligence/review/competencies");if(competenciesData)setCompetencies(competenciesData);
    const submissionsData=data<Submission[]>("/content-intelligence/review-queue");if(submissionsData)setSubmissions(submissionsData);
    const scoringData=data<ScoringItem[]>("/content-intelligence/scoring-queue");if(scoringData)setScoring(scoringData);
    const referenceData=data<Reference[]>("/content-intelligence/technical-references");if(referenceData)setReferences(referenceData);
    const manualData=data<ManualReference[]>("/content-intelligence/review/manual-references");if(manualData)setManualReferences(manualData);
    const sourceData=data<Source[]>("/content-intelligence/sources");if(sourceData)setSources(sourceData);
  },[]);
  const load=useCallback(async(force=false)=>{
    await Promise.all(activePaths.map(key=>editorialQueryCache.load(key,async()=> (await apiClient.get(key)).data,{force}).catch(()=>undefined)));
    assignCachedData();
  },[activePaths,assignCachedData]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{assignCachedData();if(historyKey){const cached=editorialQueryCache.get<Record<string,unknown>[]>(historyKey).data;if(cached)setHistory(cached);}},[assignCachedData,cacheVersion,historyKey]);
  const loading=activePaths.some(key=>editorialQueryCache.get(key).loading&&editorialQueryCache.get(key).data===undefined);
  const refreshing=activePaths.some(key=>editorialQueryCache.get(key).loading&&editorialQueryCache.get(key).data!==undefined);
  const loadErrors=activePaths.filter(key=>editorialQueryCache.get(key).error).map(key=>`${sectionName(key)} could not be loaded.`);
  // Cache changes must refresh the section badges even when the key is unchanged.
  // eslint-disable-next-line react-hooks/exhaustive-deps -- cacheVersion intentionally refreshes cached labels.
  const countLabel=useCallback((key:string)=>{const state=editorialQueryCache.get<unknown[]>(key);if(state.error&&state.data===undefined)return "Error";if(!state.data)return "—";return `${state.data.length}${state.stale?"*":""}`;},[cacheVersion]);
  const invalidateForTab=()=>tab==="review"?["/content-intelligence/review/candidates","/content-intelligence/review-queue","/content-intelligence/scoring-queue","/content-intelligence/technical-references","/content-intelligence/review/manual-references","/content-intelligence/review/competencies","/content-intelligence/interview-bank"]:tab==="sources"?["/content-intelligence/sources"]:["/content-intelligence/interview-bank"];
  const act:EditorialAction=async(work,success,invalidates)=>{setBusy(true);setMessage("");try{await work();editorialQueryCache.invalidate([...new Set([...invalidateForTab(),...(invalidates||[])])]);await load();assignCachedData();setMessage(success);}catch(error){const response=(error as {response?:{data?:{code?:string;message?:string}}})?.response?.data;setMessage(editorialActionMessage(response?.code,response?.message));}finally{setBusy(false);}};
  const tabs=useMemo(()=>[
    {id:"bank" as const,label:"Interview Bank"},
    {id:"review" as const,label:`Review Queue · ${countLabel("/content-intelligence/review/candidates")}`},
    ...(appRole==="owner"||appRole==="admin"?[{id:"sources" as const,label:"Sources"}]:[]),
  ],[appRole,countLabel]);
  return <section className="editorial-console mx-auto max-w-6xl space-y-6 text-surface-100">
    <header><p className="text-sm uppercase tracking-wider text-cyan-300">Protected editorial tools</p><h1 className="mt-2 text-3xl font-semibold">Interview Bank</h1><p className="mt-2 text-surface-300">Practice from the trusted starter bank or review new questions in one place.</p></header>
    <nav aria-label="Editorial sections" className="editorial-section-nav snap-x snap-mandatory flex gap-2 overflow-x-auto pb-2">{tabs.map(item=><button key={item.id} onClick={()=>setTab(item.id)} aria-pressed={tab===item.id} className={`min-h-11 shrink-0 snap-start rounded-lg border px-3 py-2 text-sm ${tab===item.id?"border-cyan-300 bg-cyan-950/40 text-cyan-100":"border-white/15 text-surface-300"}`}>{item.label}</button>)}</nav>
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-surface-400" aria-live="polite">{refreshing?"Refreshing saved review data…":loading?"Loading this section…":""}</p><button type="button" onClick={()=>void load(true)} className="rounded border border-white/20 px-3 py-2 text-sm">Refresh</button></div>
    {message&&<p role="status" className="rounded-lg border border-cyan-300/30 p-3 text-sm">{message}</p>}
    {loadErrors.map(error=><p key={error} role="alert" className="rounded-lg border border-amber-300/30 p-3 text-sm text-amber-100">{error} <button type="button" onClick={()=>void load(true)} className="underline">Retry</button> Other sections remain available.</p>)}
    {loading&&<div aria-label="Loading editorial section" className="space-y-3" aria-busy="true"><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{Array.from({length:5},(_,index)=><span key={index} className="h-10 animate-pulse rounded bg-white/10"/> )}</div><div className="h-28 animate-pulse rounded-xl bg-white/5"/></div>}
    {tab==="bank"&&<InterviewBankView bank={bank}/>}
    {tab==="sources"&&(appRole==="owner"||appRole==="admin")&&<><SourceRegistry sources={sources} busy={busy} act={act} onHistory={async id=>{const key=`/content-intelligence/sources/${id}/collections`;setHistoryKey(key);const result=await editorialQueryCache.load(key,async()=> (await apiClient.get(key)).data);if(Array.isArray(result))setHistory(result);}}/><details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-medium">Advanced history, trends and audit</summary><div className="mt-3 space-y-3"><div className="flex flex-wrap gap-3"><label className="text-sm">Trend window <select value={days} onChange={event=>setDays(Number(event.target.value))} className="ml-2 rounded bg-slate-800 p-2"><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select></label><button type="button" onClick={()=>void editorialQueryCache.load(`/content-intelligence/trends?days=${days}`,async()=> (await apiClient.get(`/content-intelligence/trends?days=${days}`)).data).then(value=>{if(Array.isArray(value))setTrends(value);})} className="rounded border border-white/20 px-3 py-2 text-sm">Load trends</button></div>{history.length>0&&<div className="space-y-2"><h2 className="font-medium">Collection history</h2>{history.map((row,index)=><pre key={String(row.id||index)} className="overflow-auto rounded border border-white/10 p-3 text-xs">{JSON.stringify(row,null,2)}</pre>)}</div>}{trends.map((trend,index)=><p key={`${trend.topic}-${index}`} className="text-sm">{trend.topic} · {trend.trendLabel} · {trend.distinctRecords} reviewed records</p>)}</div></details></>}
    {tab==="review"&&<ReviewQueueWorkspace candidates={candidates} submissions={submissions} scoring={scoring} references={references} manualReferences={manualReferences} competencies={competencies} busy={busy} loading={loading} act={act} search={candidateSearch} onSearch={value=>{setCandidateSearch(value);setCandidatePage(0);}} page={candidatePage} onPage={setCandidatePage} recordId={manualRecordId} setRecordId={setManualRecordId} questionText={manualQuestionText} setQuestionText={setManualQuestionText} apiRoleReady={apiRoleReady} onRetry={()=>void load(true)}/>}
  </section>;
}

function InterviewBankView({bank}:{bank:InterviewBank}){
  const [search,setSearch]=useState(""),[topic,setTopic]=useState(""),[difficulty,setDifficulty]=useState(""),[origin,setOrigin]=useState("");
  const topics=[...new Set(bank.questions.map(question=>question.topic))].sort();
  const rows=bank.questions.filter(question=>`${question.question_text} ${question.topic}`.toLowerCase().includes(search.toLowerCase())&&
    (!topic||question.topic===topic)&&(!difficulty||question.difficulty===difficulty)&&(!origin||question.origin===origin));
  const starters=bank.questions.filter(question=>question.inventory_class==="TRUSTED_BASELINE");
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-3" aria-label="Interview bank totals">
      <article className="rounded-xl border border-cyan-300/20 bg-cyan-950/20 p-4"><p className="text-sm text-surface-300">Starter Questions</p><p className="mt-1 text-3xl font-semibold">{bank.starterQuestions}</p><p className="mt-1 text-sm text-emerald-200">Ready for practice</p></article>
      <article className="rounded-xl border border-white/10 bg-slate-900/50 p-4"><p className="text-sm text-surface-300">Approved New Questions</p><p className="mt-1 text-3xl font-semibold">{bank.approvedNewQuestions}</p><p className="mt-1 text-sm text-surface-400">Reviewed and scoring-ready</p></article>
      <article className="rounded-xl border border-white/10 bg-slate-900/50 p-4"><p className="text-sm text-surface-300">Total Available</p><p className="mt-1 text-3xl font-semibold">{bank.totalAvailable}</p><p className="mt-1 text-sm text-emerald-200">Eligible for interviews</p></article>
    </div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm">Search questions<input value={search} onChange={event=>setSearch(event.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2" placeholder="Question or topic"/></label>
      <label className="text-sm">Topic<select value={topic} onChange={event=>setTopic(event.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2"><option value="">All topics</option>{topics.map(value=><option key={value}>{value}</option>)}</select></label>
      <label className="text-sm">Difficulty<select value={difficulty} onChange={event=>setDifficulty(event.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2"><option value="">All levels</option>{["easy","standard","stretch"].map(value=><option key={value}>{value}</option>)}</select></label>
      <label className="text-sm">Origin<select value={origin} onChange={event=>setOrigin(event.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2"><option value="">All origins</option>{["Aptlyra starter","User submitted","Research/import"].map(value=><option key={value}>{value}</option>)}</select></label>
    </div>
    <div className="space-y-3">{rows.map(question=><article key={question.question_version_id} className="rounded-xl border border-white/10 bg-slate-900/50 p-4">
      <h2 className="font-medium">{question.question_text}</h2><p className="mt-2 text-sm text-surface-300">{question.topic} · {question.difficulty} · {question.category}</p>
      <p className="mt-1 text-sm text-surface-400">{question.origin} · <span className="text-emerald-200">{question.display_status}</span></p>
    </article>)}</div>
    {!rows.length&&<p className="rounded-xl border border-white/10 p-5 text-sm text-surface-400">No interview questions match these filters.</p>}
    <details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-medium">Advanced / Baseline audit</summary>
      <p className="mt-2 text-sm text-surface-400">The starter bank is selected only when its published question traces to the exact approved Aptlyra-authored corpus. It uses the existing baseline evaluator. These questions do not require dynamic evidence or scoring-guide approvals.</p>
      <p className="mt-2 text-sm text-surface-300">{starters.length} trusted starter questions currently have active retrieval embeddings.</p>
    </details>
  </div>;
}

function ReviewQueueWorkspace({candidates,submissions,scoring,references,manualReferences,competencies,busy,loading,act,search,onSearch,page,onPage,recordId,setRecordId,questionText,setQuestionText,apiRoleReady,onRetry}:{candidates:Candidate[];submissions:Submission[];scoring:ScoringItem[];references:Reference[];manualReferences:ManualReference[];competencies:Competency[];busy:boolean;loading:boolean;act:EditorialAction;search:string;onSearch:(value:string)=>void;page:number;onPage:(page:number)=>void;recordId?:string;setRecordId:(value:string|undefined)=>void;questionText:string;setQuestionText:(value:string)=>void;apiRoleReady:boolean;onRetry:()=>void}){
  const knownCandidateCount=candidates.length;
  return <div className="space-y-5">
    <header><h2 className="text-xl font-semibold">Review Queue</h2><p className="mt-1 text-sm text-surface-400">Only new submissions and dynamic questions appear here. The 48 starter questions stay in Interview Bank.</p></header>
    {apiRoleReady&&<ManualQuestionComposer competencies={competencies} busy={busy} act={act} recordId={recordId} setRecordId={setRecordId} questionText={questionText} setQuestionText={setQuestionText}/>}
    <section className="space-y-3"><h3 className="font-semibold">Submissions · {submissions.length}</h3>{submissions.map(item=><article key={item.id} className="space-y-3 rounded-xl border border-white/15 bg-slate-900/60 p-4">
      <div className="flex flex-wrap justify-between gap-2"><div><h4 className="font-medium">{item.role||"Role not reported"} · {item.company_label||"company not reported"} · {item.round_type||"round unknown"}</h4><p className="mt-1 text-sm text-surface-400">{item.occurred_on||"Date unknown"} · {item.state} · {item.candidate_count} reviewed proposals</p></div><HashDisclosure label="submission hash" hash={item.content_hash}/></div>
      <details><summary className="cursor-pointer text-sm text-cyan-200">Submitted experience</summary><p className="mt-2 whitespace-pre-wrap rounded bg-slate-950/50 p-3 text-sm">{item.excerpt}</p></details>
      <div className="flex flex-wrap gap-2"><button disabled={busy||item.state!=="review_required"||!item.ai_processing_consent} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/submissions/${item.id}/extract`,{expectedHash:item.content_hash}),"AI suggestions are saved for human review; no question was approved.")} className="editorial-primary-action rounded bg-cyan-800 px-3 py-2 text-sm disabled:opacity-40">Review with AI</button>
        {apiRoleReady&&item.state==="review_required"&&<button disabled={busy} onClick={()=>{setRecordId(item.id);setQuestionText("");document.getElementById("manual-question-editor")?.scrollIntoView({behavior:"smooth",block:"center"});}} className="rounded border border-white/20 px-3 py-2 text-sm">Review manually</button>}
        {apiRoleReady&&["review_required","approved"].includes(item.state)&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/records/${item.id}/reject`,{reason:"reviewer-rejected"}),"Submission rejected.")} className="rounded border border-rose-300/40 px-3 py-2 text-sm">Reject submission</button>}
      </div>{!item.ai_processing_consent&&<p className="text-xs text-surface-400">AI review is unavailable because the submitter did not opt in. You can still review manually.</p>}
    </article>)}{!submissions.length&&<p className="rounded-xl border border-white/10 p-4 text-sm text-surface-400">No submitted questions are waiting.</p>}</section>
    {apiRoleReady&&<details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-medium">Evidence library and locally authored references</summary><div className="mt-3 space-y-4">
      <ManualReferenceWorkflow items={manualReferences} error={null} loading={loading} busy={busy} act={act} onRetry={onRetry}/>
      <ReferenceCatalog references={references} loading={loading} error={null}/>
    </div></details>}
    <section className="space-y-3"><h3 className="font-semibold">Questions · {knownCandidateCount}</h3><CandidateQueue candidates={candidates} scoring={scoring} references={references} scoringLoaded={!loading} busy={busy} act={act} search={search} onSearch={onSearch} page={page} onPage={onPage}/></section>
  </div>;
}

function ManualQuestionComposer({competencies,busy,act,recordId,setRecordId,questionText,setQuestionText}:{competencies:Competency[];busy:boolean;act:EditorialAction;recordId?:string;setRecordId:(value:string|undefined)=>void;questionText:string;setQuestionText:(value:string)=>void}){
  const [topic,setTopic]=useState(""),[mode,setMode]=useState("oral"),[difficulty,setDifficulty]=useState("standard"),[sourceNote,setSourceNote]=useState(""),[authorshipAttested,setAuthorshipAttested]=useState(false),[allowAi,setAllowAi]=useState(false);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();await act(()=>apiClient.post("/content-intelligence/review/manual-questions",{...(recordId?{recordId}:{}),question:questionText,topic,mode,difficulty,sourceNote,authorshipAttested,allowAi}),"Question saved in Review Queue for a human decision.");setQuestionText("");setSourceNote("");setTopic("");setAuthorshipAttested(false);setAllowAi(false);setRecordId(undefined);};
  return <details open={!!recordId} id="manual-question-editor" className="rounded-xl border border-cyan-300/20 bg-cyan-950/10 p-4"><summary className="cursor-pointer font-medium">{recordId?"Review this submission manually":"Add question"}</summary>
    <form onSubmit={event=>void submit(event)} className="mt-3 grid gap-3 sm:grid-cols-2">
      {recordId&&<p className="sm:col-span-2 text-sm text-surface-400">This question will remain linked to the submitter’s source record. The source record will not be published until a human approves the question.</p>}
      <label className="grid gap-1 text-sm sm:col-span-2">Question<textarea required minLength={8} maxLength={1000} value={questionText} onChange={event=>setQuestionText(event.target.value)} rows={3} className="rounded bg-slate-800 p-2" placeholder="Write a clear junior-level technical question"/></label>
      <label className="grid gap-1 text-sm">Topic<select required value={topic} onChange={event=>setTopic(event.target.value)} className="rounded bg-slate-800 p-2"><option value="">Choose a topic</option>{competencies.map(item=><option key={item.id} value={item.id}>{item.label} · {item.parentId}</option>)}</select></label>
      <label className="grid gap-1 text-sm">Difficulty<select value={difficulty} onChange={event=>setDifficulty(event.target.value)} className="rounded bg-slate-800 p-2">{["easy","standard","stretch"].map(value=><option key={value}>{value}</option>)}</select></label>
      <label className="grid gap-1 text-sm">Mode<select value={mode} onChange={event=>setMode(event.target.value)} className="rounded bg-slate-800 p-2"><option value="oral">Oral</option><option value="coding">Programming / coding</option></select></label>
      <label className="grid gap-1 text-sm">Optional source/reference note<textarea value={sourceNote} onChange={event=>setSourceNote(event.target.value)} maxLength={1000} rows={2} className="rounded bg-slate-800 p-2" placeholder="Optional provenance note. This is not treated as approved technical evidence."/></label>
      <label className="flex items-start gap-2 text-sm sm:col-span-2"><input required type="checkbox" checked={authorshipAttested} onChange={event=>setAuthorshipAttested(event.target.checked)}/>I wrote or manually reviewed this question and have the right to share it.</label>
      {!recordId&&<label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={allowAi} onChange={event=>setAllowAi(event.target.checked)}/>Allow optional AI suggestions for this authored question.</label>}
      <div className="flex gap-2 sm:col-span-2"><button disabled={busy||!competencies.length} className="rounded bg-cyan-800 px-4 py-2 text-sm disabled:opacity-40">Save to Review Queue</button>{recordId&&<button type="button" onClick={()=>{setRecordId(undefined);setQuestionText("");}} className="rounded border border-white/20 px-3 py-2 text-sm">Cancel</button>}</div>
    </form>
  </details>;
}

function editorialActionMessage(code?:string,safeMessage?:string){
  const messages:Record<string,string>={
    "review-hash-mismatch":"This content changed. Reload the latest version before approving.",
    "rubric_hash_mismatch":"This scoring packet changed. Reload the latest draft before approving.",
    "candidate-not-reviewable":"This question is no longer in a reviewable state. Refresh the queue.",
    "ai-processing-consent-required":"The submitted source does not allow AI processing, so this action is unavailable.",
    "source-ai-processing-disallowed":"The source does not permit AI processing. Review its permission before retrying.",
    "ai-review-unavailable":"AI review is unavailable. Check the configured AI service and retry.",
    "ai-provider-unavailable":"AI review is temporarily unavailable. Retry when the AI service is available.",
    "ai-provider-configuration":"AI provider configuration is unavailable. Ask an operator to check the AI service.",
    "ai-provider-rate-limited":"The AI service is rate limited. Wait briefly and retry.",
    "ai-provider-timeout":"The AI service took too long to respond. Retry shortly.",
    "invalid-ai-output":"AI returned an invalid review. Retry AI review.",
    malformed_model_json:"AI returned an invalid review format. Retry AI review.",
    editorial_schema_validation_failed:"AI returned an invalid review format. Aptlyra retried once but could not validate it.",
    editorial_semantic_validation_failed:"AI review failed a safety check. Retry AI review.",
    "database-relation-missing":"A required editorial database table or view is missing. Ask an operator to apply the latest Aptlyra migrations.",
    "database-column-missing":"A required editorial database column is missing. Ask an operator to apply the latest Aptlyra migrations.",
    "database-integrity-conflict":"The editorial change conflicts with a database integrity rule. Refresh the item and retry.",
    "database-connection-failed":"The editorial database is temporarily unreachable. Retry shortly.",
    "database-data-invalid":"The editorial data did not match the database format. Refresh the item and retry.",
    "database-operation-failed":"The editorial database could not complete this action. Share the request ID with an operator.",
    "seed-source-permission-not-enabled":"The database needs the latest editorial migration before starter questions can be reviewed.",
    "seed-review-schema-unavailable":"The database needs the latest editorial migration before starter questions can be loaded.",
    "invalid-review-output":"The AI response did not match the review format. Retry after checking the AI service.",
    "reviewer-not-authorized":"Your reviewer access is no longer active. Ask an owner to check your access.",
    "approved_reference_required":"Approve a technical reference before drafting the scoring rubric.",
    "technical-reference-required":"Approve a technical reference before drafting the scoring rubric.",
    "editorial-action-failed":"The review could not be saved. Refresh this section and retry.",
  };
  return code&&messages[code]||safeMessage||"The review action could not be completed. Refresh this section and retry.";
}

function sectionName(key:string){if(key.includes("seed-review"))return "Starter questions";if(key.includes("manual-references")||key.includes("technical-references"))return "Evidence";if(key.includes("review/candidates"))return "Questions";if(key.includes("review-queue"))return "Submissions";if(key.includes("scoring-queue"))return "Scoring";if(key.includes("published"))return "Published questions";if(key.includes("sources"))return "Sources";if(key.includes("trends"))return "Trends";return "Editorial data";}

function HashDisclosure({label,hash}:{label:string;hash:string}){const [copied,setCopied]=useState(false);return <details className="text-xs text-surface-400"><summary className="cursor-pointer">Advanced details · {label} {hash.slice(0,8)}…</summary><div className="mt-1 flex flex-wrap items-center gap-2"><code className="break-all">{hash}</code><button type="button" onClick={()=>void navigator.clipboard?.writeText(hash).then(()=>{setCopied(true);window.setTimeout(()=>setCopied(false),1500);})} className="rounded border border-white/15 px-2 py-1">{copied?"Copied":"Copy full hash"}</button></div></details>}

function AIReviewProposal({review}:{review:SavedAIReview}){const packet=review.packet;return <details className="rounded border border-cyan-300/20 bg-cyan-950/10 p-3 text-sm"><summary className="cursor-pointer text-cyan-200">AI suggestions · review before approving</summary><div className="mt-3 space-y-2"><p><strong>Recommendation:</strong> {packet.verdict.replaceAll("recommend-","")} · {packet.confidence} confidence</p>{packet.correctedQuestion&&<p><strong>Suggested wording:</strong> {packet.correctedQuestion}</p>}<p><strong>Topic:</strong> {packet.category} · {packet.difficulty}</p><p><strong>What a good answer should cover:</strong> {packet.expectedConcepts.join(" · ")}</p><p><strong>Evidence status:</strong> {packet.evidenceStatus} — {packet.evidenceSummary}</p>{packet.wordingIssues.length>0&&<p><strong>Warnings:</strong> {packet.wordingIssues.join(" · ")}</p>}<details><summary className="cursor-pointer text-xs text-surface-400">Advanced AI review details</summary><p className="mt-2">Taxonomy {packet.taxonomyRoot||"root"} / {packet.taxonomy} · technical correctness {packet.technicalCorrectness} · references {packet.referenceStatus||"unknown"} ({packet.eligibleReferenceCount??0}) · flags {packet.flags.join(" · ")||"none"}</p><HashDisclosure label="AI proposal hash" hash={review.hash}/><p className="text-xs text-surface-400">Version {review.version}, saved {review.createdAt}. Human approval is still required.</p></details><p className="text-xs text-surface-400">AI suggestions do not change the question or approve it.</p></div></details>}

function candidateStatus(item:Candidate){if(item.state==="rejected")return "Rejected";if(item.state==="published")return "Needs evidence";if(item.state==="approved")return "Needs publication check";return item.ai_review?"Needs your decision":"Needs human review · AI suggestions optional";}
function scoringStatus(item:ScoringItem){if(item.publication_class==="reviewed/scoring-ready")return "Ready for interview";if(!item.technical_references?.some(ref=>ref.state==="approved"))return "Needs evidence";if(!(item.rubric_hash||item.scoring_packet_hash))return "Needs scoring guide";return "Needs retrieval check";}

function CandidateQueue({candidates,scoring,references,scoringLoaded,busy,act,search,onSearch,page,onPage}:{candidates:Candidate[];scoring:ScoringItem[];references:Reference[];scoringLoaded:boolean;busy:boolean;act:EditorialAction;search:string;onSearch:(value:string)=>void;page:number;onPage:(page:number)=>void}){
  const filtered=candidates.filter(item=>`${item.source_name} ${item.role||""} ${item.company_label||""} ${String(item.specification.text||"")}`.toLowerCase().includes(search.toLowerCase()));
  const start=page*10,items=filtered.slice(start,start+10);
  const optionalAI=candidates.filter(item=>item.state==="review_required"&&!item.ai_review).length,needsHuman=candidates.filter(item=>item.state==="review_required").length;
  const needsEvidence=scoringLoaded?scoring.filter(item=>!item.technical_references?.some(ref=>ref.state==="approved")).length:"—";
  const needsRubric=scoringLoaded?scoring.filter(item=>item.technical_references?.some(ref=>ref.state==="approved")&&!item.rubric_hash).length:"—";
  return <div className="space-y-4"><ol aria-label="New-content review status" className="flex flex-wrap gap-2 text-xs"><li className="rounded bg-white/5 px-2 py-1">Optional AI suggestions · {optionalAI}</li><li className="rounded bg-white/5 px-2 py-1">Human decision required · {needsHuman}</li><li className="rounded bg-white/5 px-2 py-1">Evidence needed · {needsEvidence}</li><li className="rounded bg-white/5 px-2 py-1">Scoring guide needed · {needsRubric}</li></ol><label className="block text-sm">Find a question<input value={search} onChange={event=>onSearch(event.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2" placeholder="Search question, role or source"/></label><div className="space-y-4">{items.map(item=>{const scoringForQuestion=scoring.filter(row=>row.candidate_id===item.candidate_id);return <section key={item.candidate_id} className="space-y-3"><CandidateCard item={item} candidates={candidates} busy={busy} act={act}/>{scoringForQuestion.map(scoringItem=><ScoringCard key={scoringItem.question_version_id} item={scoringItem} references={references} busy={busy} act={act}/>)}</section>;})}</div>
    {scoringLoaded&&scoring.filter(item=>!candidates.some(candidate=>candidate.candidate_id===item.candidate_id)).map(item=><ScoringCard key={item.question_version_id} item={item} references={references} busy={busy} act={act}/>)}
    <QueuePager page={page} total={filtered.length} onPage={onPage}/>{!filtered.length&&<p className="rounded-xl border border-white/10 p-5 text-sm text-surface-400">{search?"No questions match this search.":"No new questions are waiting for review."}</p>}</div>;
}

function QueuePager({page,total,onPage}:{page:number;total:number;onPage:(page:number)=>void}){const pages=Math.ceil(total/10);return pages>1?<nav aria-label="Queue pages" className="flex items-center justify-between"><button disabled={page===0} onClick={()=>onPage(page-1)} className="rounded border border-white/15 px-3 py-2 text-sm disabled:opacity-40">Previous</button><span className="text-sm">Page {page+1} of {pages}</span><button disabled={page+1>=pages} onClick={()=>onPage(page+1)} className="rounded border border-white/15 px-3 py-2 text-sm disabled:opacity-40">Next</button></nav>:null;}

function ReferenceCatalog({references,loading,error}:{references:Reference[];loading:boolean;error:string|null}){return <section className="space-y-3"><h2 className="font-semibold">Approved technical references</h2>{error&&<p role="alert" className="rounded-xl border border-amber-300/30 p-4 text-sm">Evidence could not be loaded.</p>}{references.map(reference=><article key={reference.chunk_id} className="rounded-xl border border-white/10 p-4"><h3 className="font-medium">{reference.source_title} · v{reference.version}</h3><p className="mt-1 text-xs text-surface-400">{reference.origin} · {reference.license_id||"license unspecified"}</p><details className="mt-2"><summary className="cursor-pointer text-sm text-cyan-200">Read permitted excerpt</summary><p className="mt-2 whitespace-pre-wrap text-sm">{reference.text}</p></details></article>)}{loading&&!references.length&&<p role="status" className="h-12 animate-pulse rounded bg-white/5"/>}{!loading&&!error&&!references.length&&<p className="rounded-xl border border-white/10 p-4 text-sm text-surface-400">No technical references yet.</p>}</section>;}

function ManualReferenceWorkflow({items,error,loading,busy,act,onRetry}:{items:ManualReference[];error:string|null;loading:boolean;busy:boolean;act:EditorialAction;onRetry:()=>void}){
  const [title,setTitle]=useState(""),[sourceName,setSourceName]=useState(""),[content,setContent]=useState(""),[provenance,setProvenance]=useState(""),[attested,setAttested]=useState(false);
  const save=async()=>{await act(()=>apiClient.post("/content-intelligence/review/manual-references",{title,text:content,permissionEvidence:provenance,attribution:sourceName,authorshipAttested:attested}),"Reference saved for human review.",["/content-intelligence/review/manual-references","/content-intelligence/technical-references","/content-intelligence/scoring-queue","/content-intelligence/seed-review","/content-intelligence/published"]);setTitle("");setSourceName("");setContent("");setProvenance("");setAttested(false);};
  return <section className="space-y-3 rounded-xl border border-white/10 p-4"><div><h2 className="font-semibold">Add a technical reference</h2><p className="mt-1 text-sm text-surface-400">Save a source with its provenance. A reviewer must approve it before it supports a question.</p></div>{error&&<p role="alert" className="text-sm text-amber-100">Evidence could not be loaded. <button type="button" onClick={onRetry} className="underline">Retry</button></p>}{loading&&!items.length&&<p role="status" className="h-8 animate-pulse rounded bg-white/5"/>}{items.map(item=><article key={item.record_id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-white/10 p-3"><div><h3 className="font-medium">{item.title}</h3><p className="text-xs text-surface-400">{item.source_name} · Pending human approval</p></div><button type="button" disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/manual-references/${item.record_id}/approve`,{expectedHash:item.content_hash}),"Reference approved and available for question evidence.",["/content-intelligence/review/manual-references","/content-intelligence/technical-references","/content-intelligence/review/candidates","/content-intelligence/scoring-queue","/content-intelligence/seed-review","/content-intelligence/published"])} className="editorial-primary-action rounded bg-cyan-800 px-3 py-2 text-sm disabled:opacity-40">Approve reference</button></article>)}<details><summary className="cursor-pointer text-sm text-cyan-200">Add reference</summary><form className="mt-3 grid gap-3" onSubmit={event=>{event.preventDefault();void save();}}><label className="grid gap-1 text-sm">Title<input required value={title} onChange={event=>setTitle(event.target.value)} className="rounded bg-slate-800 p-2"/></label><label className="grid gap-1 text-sm">Source or author<input required value={sourceName} onChange={event=>setSourceName(event.target.value)} className="rounded bg-slate-800 p-2"/></label><label className="grid gap-1 text-sm">Reference content<textarea required value={content} onChange={event=>setContent(event.target.value)} rows={4} className="rounded bg-slate-800 p-2"/></label><label className="grid gap-1 text-sm">Where this came from<input required value={provenance} onChange={event=>setProvenance(event.target.value)} className="rounded bg-slate-800 p-2"/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={attested} onChange={event=>setAttested(event.target.checked)}/>I have the right to share this material and it contains no private or confidential information.</label><button type="submit" disabled={busy||!attested} className="editorial-primary-action w-full rounded bg-cyan-800 px-4 py-3 text-sm disabled:opacity-40 sm:w-auto">Save for review</button></form></details></section>;
}


function CandidateCard({item,candidates,busy,act}:{item:Candidate;candidates:Candidate[];busy:boolean;act:EditorialAction}){
  const [text,setText]=useState(String(item.specification.text||"")),[duplicateDecision,setDuplicateDecision]=useState(item.duplicate_links?.some(link=>link.kind==="exact")?"":"distinct"),[relation,setRelation]=useState<"duplicate"|"family"|"supersede"|null>(null);
  const encoded=encodeURIComponent(item.candidate_id),expectedHash=item.content_hash,reviewable=item.state==="review_required";
  const consentAllowed=item.model_processing_allowed===true&&(item.source_type!=="user_submission"||item.ai_processing_consent===true);
  return <article className="space-y-3 rounded-xl border border-white/15 bg-slate-900/60 p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{item.role||"Interview question"}</h2><p className="text-sm text-cyan-200">{candidateStatus(item)}</p><p className="text-xs text-surface-400">{item.source_name} · {item.role}{item.company_label?` · ${item.company_label}`:""}</p></div><details className="text-xs text-surface-400"><summary className="cursor-pointer">Advanced source details</summary><p className="mt-1">{item.source_type} · {item.permission_status}/{item.review_status} · {item.occurred_on||"date unknown"} · {item.round_type||"round unknown"} · derivation {item.derivation_type} · confidence {item.confidence??"not provided"}</p><HashDisclosure label="question hash" hash={expectedHash}/></details></div>
    <p className="rounded bg-slate-950/50 p-3 text-sm">{String(item.specification.text||"")}</p>
    {!item.ai_review&&<><button disabled={busy||!consentAllowed} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/ai-review`,{expectedHash}),"AI suggestions are ready. Review them before deciding.")} className="editorial-primary-action rounded bg-cyan-800 px-3 py-2 text-sm disabled:opacity-40">Review with AI</button><span className="text-xs text-surface-400">Optional. You can review and decide manually without AI.</span></>}{!consentAllowed&&<span className="text-xs text-amber-200">AI suggestions are unavailable because the source did not allow model processing. Manual review remains available.</span>}
    {item.ai_review&&<AIReviewProposal review={item.ai_review}/>}
    {reviewable&&item.ai_review&&<button disabled={busy||(Boolean(item.duplicate_links?.length)&&!duplicateDecision)} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/approve`,{expectedHash,duplicateDecision:duplicateDecision||undefined}),"Question approved.")} className="editorial-primary-action rounded bg-emerald-700 px-3 py-2 text-sm disabled:opacity-40">Approve question</button>}
    {item.state==="approved"&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/publish`,{expectedHash}),"Question published. Evidence and scoring guide still need review.")} className="editorial-primary-action rounded bg-cyan-700 px-3 py-2 text-sm">Continue review</button>}
    {typeof item.extraction_metadata?.evidenceText==="string"&&<p className="rounded border border-cyan-300/20 bg-cyan-950/20 p-3 text-sm">Evidence span ({String(item.extraction_metadata.evidenceStart)}–{String(item.extraction_metadata.evidenceEnd)}): “{item.extraction_metadata.evidenceText}” · {String(item.extraction_metadata.language||"language unknown")}</p>}
    <details><summary className="cursor-pointer text-sm text-cyan-200">Permitted evidence excerpt</summary><p className="mt-2 whitespace-pre-wrap rounded bg-slate-950/50 p-3 text-sm">{item.normalized_text}</p></details>
    {item.duplicate_links?.length>0&&<p className="text-sm text-amber-200">Possible duplicates: {item.duplicate_links.map(v=>`${v.candidateId} (${v.kind}, ${v.similarity})`).join(" · ")}</p>}
    <details className="rounded border border-white/10 p-3"><summary className="cursor-pointer text-sm text-cyan-200">Review manually · edit, approve or reject</summary><div className="mt-3 space-y-3"><label className="block text-sm">Question<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={12000} rows={3} className="mt-1 w-full rounded bg-slate-800 p-3"/></label>
    <div className="flex flex-wrap gap-2">
      {item.duplicate_links?.length>0&&<select aria-label="Duplicate review decision" value={duplicateDecision} onChange={e=>setDuplicateDecision(e.target.value)} className="rounded bg-slate-800 px-2 text-sm"><option value="">Resolve exact duplicate first</option><option value="distinct">Keep distinct</option><option value="retain-provenance">Retain exact duplicate provenance</option></select>}
      {!item.ai_review&&<button disabled={busy||!reviewable||(Boolean(item.duplicate_links?.length)&&!duplicateDecision)} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/approve`,{expectedHash,duplicateDecision:duplicateDecision||undefined}),"Human question approval recorded without AI suggestions.")} className="rounded border border-emerald-300/40 px-3 py-2 text-sm">Approve manually</button>}
      <button disabled={busy||!reviewable||!text.trim()} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/edit-approve`,{expectedHash,specification:{...item.specification,text},derivation:"paraphrased"}),"Edited question approved by a human reviewer.")} className="rounded bg-cyan-800 px-3 py-2 text-sm">Edit and approve</button>
      <button disabled={busy||!reviewable} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/reject`,{expectedHash,reason:"reviewer-rejected"}),"Question rejected.")} className="rounded bg-rose-900 px-3 py-2 text-sm">Reject</button>
      <button disabled={busy||!reviewable} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/withdraw`,{expectedHash,reason:"reviewer-withdrawn"}),"Question withdrawn.")} className="rounded border border-white/20 px-3 py-2 text-sm">Withdraw</button>
    </div></div></details>
    <details className="rounded border border-white/10 p-3"><summary className="cursor-pointer text-sm text-surface-300">Advanced review actions</summary><div className="mt-3 flex flex-wrap gap-2">{item.duplicate_links?.length>0&&<label className="text-xs">Duplicate decision <select aria-label="Duplicate review decision" value={duplicateDecision} onChange={e=>setDuplicateDecision(e.target.value)} className="ml-2 rounded bg-slate-800 p-2"><option value="">Choose before approval</option><option value="distinct">Keep distinct</option><option value="retain-provenance">Retain exact duplicate provenance</option></select></label>}<button disabled={busy||!reviewable} onClick={()=>setRelation("duplicate")} className="rounded border border-amber-400/50 px-3 py-2 text-sm">Mark duplicate…</button><button disabled={busy} onClick={()=>setRelation("family")} className="rounded border border-amber-300/40 px-3 py-2 text-sm">Link question family…</button><button disabled={busy||item.state!=="published"} onClick={()=>setRelation("supersede")} className="rounded border border-cyan-300/40 px-3 py-2 text-sm">Supersede question…</button></div></details>
    {relation&&<CandidateRelationDialog kind={relation} candidates={candidates.filter(candidate=>candidate.candidate_id!==item.candidate_id&& (relation==="supersede"?candidate.state==="published":["approved","published"].includes(candidate.state)))} onClose={()=>setRelation(null)} onConfirm={id=>{setRelation(null);const route=relation==="duplicate"?"duplicate":relation==="family"?"family":"supersede";const body=relation==="duplicate"?{expectedHash,duplicateOf:id,reason:"duplicate-family"}:relation==="family"?{expectedHash,relatedId:id}:{expectedHash,supersedesId:id};const success=relation==="duplicate"?"Duplicate link recorded.":relation==="family"?"Question family linked for reviewer context.":"Published question superseded; existing session snapshots remain readable.";void act(()=>apiClient.post(`/content-intelligence/review/candidates/${encoded}/${route}`,body),success);}}/>}
  </article>;
}

function CandidateRelationDialog({kind,candidates,onClose,onConfirm}:{kind:"duplicate"|"family"|"supersede";candidates:Candidate[];onClose:()=>void;onConfirm:(id:string)=>void}){const [search,setSearch]=useState(""),[page,setPage]=useState(0),[selected,setSelected]=useState("");const filtered=candidates.filter(candidate=>String(candidate.specification.text||candidate.candidate_id).toLowerCase().includes(search.toLowerCase()));const rows=filtered.slice(page*8,page*8+8);const title=kind==="duplicate"?"Mark an existing question as duplicate":kind==="family"?"Link a related question family":"Choose the question being superseded";return <div role="dialog" aria-modal="true" aria-labelledby="relation-dialog-title" className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-4"><section className="max-h-[85vh] w-full max-w-2xl space-y-4 overflow-y-auto rounded-xl border border-white/20 bg-slate-900 p-5"><h2 id="relation-dialog-title" className="text-lg font-semibold">{title}</h2><label className="block text-sm">Search questions<input autoFocus value={search} onChange={event=>{setSearch(event.target.value);setPage(0);}} className="mt-1 w-full rounded bg-slate-800 p-2"/></label><ul className="space-y-2">{rows.map(candidate=><li key={candidate.candidate_id}><button type="button" aria-pressed={selected===candidate.candidate_id} onClick={()=>setSelected(candidate.candidate_id)} className={`w-full rounded border p-3 text-left text-sm ${selected===candidate.candidate_id?"border-cyan-300":"border-white/10"}`}>{String(candidate.specification.text||candidate.candidate_id).slice(0,240)}</button></li>)}</ul>{!rows.length&&<p className="text-sm text-surface-400">No matching questions.</p>}<div className="flex items-center justify-between text-sm"><button disabled={page===0} onClick={()=>setPage(page-1)} className="rounded border border-white/15 px-3 py-2 disabled:opacity-40">Previous</button><span>{filtered.length?`${page+1} / ${Math.ceil(filtered.length/8)}`:"0 results"}</span><button disabled={(page+1)*8>=filtered.length} onClick={()=>setPage(page+1)} className="rounded border border-white/15 px-3 py-2 disabled:opacity-40">Next</button></div><footer className="flex justify-end gap-2"><button onClick={onClose} className="rounded border border-white/20 px-3 py-2">Cancel</button><button disabled={!selected} onClick={()=>onConfirm(selected)} className="rounded bg-cyan-800 px-3 py-2 disabled:opacity-40">Confirm selection</button></footer></section></div>;}

function ScoringCard({item,references,busy,act}:{item:ScoringItem;references:Reference[];busy:boolean;act:EditorialAction}){
  const [chunkId,setChunkId]=useState(""),[edits,setEdits]=useState<Record<string,string>>({});
  const hasReference=item.technical_references?.some(ref=>ref.state==="approved")||Boolean(item.is_seed&&(item.reviewed_reference_count||0)>0),hasRubric=Boolean(item.rubric_hash||item.scoring_packet_hash),isReady=item.publication_class==="reviewed/scoring-ready";
  const nextStep=isReady?"This question can be used in interviews.":!hasReference?"Add at least one approved technical reference before publishing this scored question.":!hasRubric?"Draft and approve a scoring guide.":"Finish the retrieval check.";
  return <article className="space-y-3 rounded-xl border border-white/15 bg-slate-900/60 p-4">
    <div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">{item.question_text}</h2><span className="text-sm text-cyan-200">{scoringStatus(item)}</span></div></div>
    <ol aria-label="Question scoring readiness" className="flex flex-wrap gap-2 text-xs"><li className="rounded bg-emerald-950/50 px-2 py-1 text-emerald-200">1 · Human question review · AI optional</li><li className={`rounded px-2 py-1 ${hasReference?"bg-emerald-950/50 text-emerald-200":"bg-white/5 text-surface-400"}`}>2 · Evidence</li><li className={`rounded px-2 py-1 ${hasRubric?"bg-emerald-950/50 text-emerald-200":"bg-white/5 text-surface-400"}`}>3 · Scoring guide</li><li className={`rounded px-2 py-1 ${isReady?"bg-emerald-950/50 text-emerald-200":"bg-white/5 text-surface-400"}`}>4 · Ready</li></ol><p className="text-sm text-surface-300">Next: {nextStep}</p>
    <HashDisclosure label="question hash" hash={item.content_hash}/>
    {item.candidate_id&&<><button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${item.candidate_id}/ai-review`,{expectedHash:item.content_hash}),"AI suggestions are ready. Review them before deciding.",["/content-intelligence/review/candidates","/content-intelligence/seed-review"])} className="editorial-primary-action rounded border border-cyan-300/40 px-3 py-2 text-sm">{item.ai_review?"Review again with AI":"Ask AI to review"}</button>{item.ai_review&&<AIReviewProposal review={item.ai_review}/>}</>}
    {item.is_seed&&item.candidate_id&&item.ai_review&&!item.seed_question_approved&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/review/candidates/${item.candidate_id}/approve-seed-question`,{expectedHash:item.content_hash,expectedPacketHash:item.ai_review!.hash}),"Human decision recorded for this exact question and AI proposal. Evidence, rubric and embedding checks remain.")} className="rounded bg-emerald-700 px-3 py-2 text-sm disabled:opacity-40">Approve seed question as written</button>}
    {item.is_seed&&item.seed_question_approved&&<p role="status" className="text-sm text-emerald-200">Human question decision recorded for the current content and AI proposal.</p>}
    <h3 className="font-medium">Scoring guide</h3><p className="text-sm text-surface-400">A scoring guide defines what a strong answer should include.</p>
    <p className="text-sm">Approved evidence: {item.technical_references?.filter(ref=>ref.state==="approved").length||0} · Scoring guide: {item.rubric_kind||"not drafted"}</p>
    {!hasReference&&<p className="rounded border border-amber-300/20 p-3 text-sm text-amber-100">Add at least one approved technical reference before publishing this scored question.</p>}
    {item.technical_references?.filter(ref=>ref.state==="approved").map(ref=><details key={ref.chunkId} className="rounded border border-white/10 p-3"><summary className="cursor-pointer text-sm">{ref.sourceTitle} · v{ref.version}</summary><div className="mt-2"><HashDisclosure label="technical reference hash" hash={ref.hash}/><HashDisclosure label="reference chunk hash" hash={ref.chunkHash}/><HashDisclosure label="permission evidence hash" hash={ref.permissionHash}/></div><p className="mt-2 text-xs text-surface-400">Source {ref.sourceId} · document {ref.documentVersionId} · chunk {ref.chunkId} · offsets {ref.startOffset}–{ref.endOffset} · license {ref.licenseId||"not specified"}</p><p className="mt-2 whitespace-pre-wrap text-sm text-surface-300">{ref.text}</p><button disabled={busy} onClick={()=>void act(()=>apiClient.delete(`/content-intelligence/scoring/${item.question_version_id}/references/${ref.chunkId}`),"Reference removed from future scoring eligibility.")} className="mt-2 text-sm text-rose-300 underline">Remove reference</button></details>)}
    {item.rubric_content&&<div className="rounded border border-white/10 p-3"><HashDisclosure label="approved rubric hash" hash={item.rubric_hash||""}/><ul className="mt-2 list-disc pl-5 text-sm">{item.rubric_content.concepts.map(concept=><li key={concept.key}>{concept.label} · weight {concept.importance} · {concept.required?"required":"supporting"} — {concept.description}</li>)}</ul></div>}
    {item.rubric_content&&<Guidance packet={item.rubric_content}/>}
    <div className="flex flex-wrap gap-2"><select value={chunkId} onChange={e=>setChunkId(e.target.value)} aria-label="Technical reference" className="max-w-xl rounded bg-slate-800 px-3 py-2 text-sm"><option value="">Select permitted technical reference</option>{references.map(ref=><option key={ref.chunk_id} value={ref.chunk_id}>{ref.source_title} · {ref.license_id||"license unspecified"} · v{ref.version}</option>)}</select>
      <button disabled={busy||!chunkId} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/${item.question_version_id}/references`,{chunkId}),"Technical reference attached and approved.")} className="rounded border border-white/20 px-3 py-2 text-sm">Add reference</button>
      <button disabled={busy||!(item.technical_references?.some(ref=>ref.state==="approved"))} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/${item.question_version_id}/draft`),"A scoring guide draft is ready for your review.")} className="editorial-primary-action rounded bg-cyan-800 px-3 py-2 text-sm">{item.drafts?.length?"Draft again":"Draft scoring guide"}</button>
      {item.rubric_hash&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/${item.question_version_id}/withdraw`,{expectedHash:item.rubric_hash}),"Scoring packet withdrawn from future use.")} className="rounded border border-rose-400/40 px-3 py-2 text-sm">Withdraw packet</button>}</div>
    {(item.drafts||[]).map(draft=><div key={draft.id} className="rounded border border-white/10 p-3"><HashDisclosure label="draft rubric hash" hash={draft.hash}/><ul className="my-2 list-disc pl-5 text-sm">{draft.content.concepts.map(c=><li key={c.key}>{c.label} — {c.description}</li>)}</ul><Guidance packet={draft.content}/>
      <label className="block text-xs text-surface-400">Edit packet JSON<textarea aria-label={`Edit scoring packet ${draft.id}`} value={edits[draft.id]??JSON.stringify(draft.content,null,2)} onChange={e=>setEdits(current=>({...current,[draft.id]:e.target.value}))} rows={8} className="mt-1 w-full rounded bg-slate-950 p-2 font-mono text-xs"/></label>
      <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>{try{const content=JSON.parse(edits[draft.id]??JSON.stringify(draft.content));void act(()=>apiClient.post(`/content-intelligence/scoring/drafts/${draft.id}/edit`,{expectedHash:draft.hash,content}),"Edited scoring guide saved as a new draft.");}catch{setEdits(current=>({...current,[draft.id]:current[draft.id]||""}));}}} className="rounded border border-white/20 px-3 py-2 text-sm">Save edited guide</button><button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/drafts/${draft.id}/approve`,{expectedHash:draft.hash}),"Question approved for interviews with its scoring guide.")} className="editorial-primary-action rounded bg-emerald-700 px-3 py-2 text-sm">Approve for interviews</button><button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/scoring/drafts/${draft.id}/reject`,{expectedHash:draft.hash,reason:"scoring-rejected"}),"Scoring guide declined.")} className="rounded bg-rose-900 px-3 py-2 text-sm">Reject guide</button></div>
    </div>)}
  </article>;
}

function Guidance({packet}:{packet:ScoringPacket}){return <details className="rounded border border-white/10 p-3 text-sm"><summary className="cursor-pointer text-cyan-200">Evidence and learning guidance</summary><div className="mt-3 space-y-2">
  {(packet.evidenceIndicators||[]).map((item,index)=><p key={`e${index}`}><strong>{item.conceptKey} evidence:</strong> Supported: {item.supportedEvidence.join("; ")||"none specified"}. Gaps: {item.missingEvidence.join("; ")||"none specified"}.</p>)}
  {(packet.misconceptions||[]).map((item,index)=><p key={`m${index}`}><strong>{item.conceptKey} misconception:</strong> {item.description}</p>)}
  {(packet.dimensionGuidance||[]).map((item,index)=><p key={`d${index}`}><strong>{item.dimension}:</strong> {item.guidance}</p>)}
  {(packet.followUpConcepts||[]).map(item=><p key={`f${item.key}`}><strong>Follow-up {item.label}:</strong> {item.description}</p>)}
  {packet.codingObjectiveEvidence&&<p><strong>Coding objective:</strong> {packet.codingObjectiveEvidence.objective} Evidence: {packet.codingObjectiveEvidence.successEvidence.join("; ")}.</p>}
  {!packet.evidenceIndicators?.length&&!packet.misconceptions?.length&&!packet.dimensionGuidance?.length&&!packet.followUpConcepts?.length&&!packet.codingObjectiveEvidence&&<p className="text-surface-400">No additional editorial guidance is attached.</p>}
</div></details>}

function SourceRegistry({sources,busy,act,onHistory}:{sources:Source[];busy:boolean;act:EditorialAction;onHistory:(id:string)=>Promise<void>}){
  const [now,setNow]=useState<number|null>(null);
  useEffect(()=>{const refresh=()=>setNow(Date.now());refresh();const timer=window.setInterval(refresh,60_000);return()=>window.clearInterval(timer);},[]);
  const [name,setName]=useState(""),[type,setType]=useState("rss_atom"),[baseUrl,setBaseUrl]=useState(""),[termsUrl,setTermsUrl]=useState(""),[basis,setBasis]=useState(""),[evidence,setEvidence]=useState(""),[permissionExpiry,setPermissionExpiry]=useState(""),[attribution,setAttribution]=useState(""),[interval,setInterval]=useState(1440),[retention,setRetention]=useState(7),[fullText,setFullText]=useState(false),[derived,setDerived]=useState(true),[modelProcessing,setModelProcessing]=useState(false),[hosts,setHosts]=useState(""),[paths,setPaths]=useState(""),[editingId,setEditingId]=useState<string|null>(null);
  const edit=(source:Source)=>{setEditingId(source.id);setName(source.name);setType(source.source_type);setBaseUrl(source.base_url);setTermsUrl(source.terms_url);setBasis(source.permission_basis);setEvidence(source.permission_evidence);setPermissionExpiry(source.permission_expires_at?new Date(new Date(source.permission_expires_at).getTime()-new Date(source.permission_expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):"");setAttribution(source.attribution||"");setInterval(source.collection_interval_minutes);setRetention(Math.round(source.raw_retention_seconds/86400));setFullText(source.full_text_storage);setDerived(source.derived_facts_storage);setModelProcessing(source.model_processing_allowed);setHosts(source.allowed_scope.allowedHosts.join(","));setPaths(source.allowed_scope.allowedPaths.join(","));};
  const create=()=>{let host="",path="/";try{const url=new URL(baseUrl);host=url.hostname;path=url.pathname;}catch{/* API returns a safe validation error. */}const value={name,sourceType:type,baseUrl,termsUrl,permissionBasis:basis,permissionEvidence:evidence,permissionExpiresAt:permissionExpiry?new Date(permissionExpiry).toISOString():null,attribution,intervalMinutes:interval,rawRetentionDays:retention,fullTextStorage:fullText,derivedDataStorage:derived,modelProcessingAllowed:modelProcessing,allowedHosts:hosts.split(",").map(x=>x.trim()).filter(Boolean).length?hosts.split(",").map(x=>x.trim()):[host],allowedPaths:paths.split(",").map(x=>x.trim()).filter(Boolean).length?paths.split(",").map(x=>x.trim()).filter(Boolean):[path]};return act(()=>editingId?apiClient.patch(`/content-intelligence/sources/${editingId}`,value):apiClient.post("/content-intelligence/sources",value),editingId?"Source updated. Permission-relevant changes require a new human review and leave the source disabled.":"Source created disabled. A linked human must review the exact permission evidence before enabling collection.");};
  return <div className="space-y-5"><p className="rounded border border-cyan-300/20 p-3 text-sm text-surface-300">The backend does not search the internet automatically. Only configured, permission-reviewed, enabled sources are collected. Sources (0) means no external collection. Scheduled collection runs only while the backend worker runtime is running.</p><details open={!!editingId} className="rounded-xl border border-white/15 p-4"><summary className="cursor-pointer font-semibold">{editingId?"Edit source configuration":"Register a source (starts disabled)"}</summary><form onSubmit={event=>{event.preventDefault();void create();}} className="mt-3 grid gap-3 md:grid-cols-2">
    <h2 className="md:col-span-2 font-semibold">Permission details</h2>
    <label className="text-sm">Display name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Source adapter<select value={type} onChange={e=>setType(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"><option value="rss_atom">RSS / Atom</option><option value="official_api">REST / JSON API</option></select></label>
    <label className="text-sm">Feed/API URL<input required type="url" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Terms URL<input required type="url" value={termsUrl} onChange={e=>setTermsUrl(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Permission basis<input required value={basis} onChange={e=>setBasis(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Permission evidence<textarea required value={evidence} onChange={e=>setEvidence(e.target.value)} rows={2} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Permission expires (optional)<input type="datetime-local" value={permissionExpiry} onChange={e=>setPermissionExpiry(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/><span className="mt-1 block text-xs text-surface-400">Expired permission disables future collection and removes linked content from new planner/trend results. Updating expiry requires a fresh exact-hash review.</span></label>
    <label className="text-sm">Allowed hosts (comma-separated)<input value={hosts} onChange={e=>setHosts(e.target.value)} placeholder="derived from URL when blank" className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Allowed paths<input value={paths} onChange={e=>setPaths(e.target.value)} placeholder="feed path used when blank" className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Collection interval (minutes)<input type="number" min={60} max={10080} value={interval} onChange={e=>setInterval(Number(e.target.value))} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Raw content retention (days)<input type="number" min={0} max={30} value={retention} onChange={e=>setRetention(Number(e.target.value))} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="text-sm">Attribution requirements<input value={attribution} onChange={e=>setAttribution(e.target.value)} className="mt-1 block w-full rounded bg-slate-800 p-2"/></label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={fullText} onChange={e=>setFullText(e.target.checked)}/>Permission allows full text storage</label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={derived} onChange={e=>setDerived(e.target.checked)}/>Permission allows derived metadata storage</label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={modelProcessing} onChange={e=>setModelProcessing(e.target.checked)}/>Written permission allows model processing</label>
    <button disabled={busy} className="rounded bg-cyan-800 px-3 py-2 text-sm disabled:opacity-40">{editingId?"Save source configuration":"Create disabled source"}</button>{editingId&&<button type="button" onClick={()=>setEditingId(null)} className="rounded border border-white/20 px-3 py-2 text-sm">Cancel edit</button>}
  </form></details><div className="space-y-3">{sources.map(source=><SourceRowErrorBoundary key={source.id}><article className="space-y-3 rounded-xl border border-white/15 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold">{source.name}</h2><p className="text-xs text-surface-400">{source.source_type} · {source.permission_status} / {source.review_status} · {source.state}</p></div><span className="text-sm">{source.last_safe_result?`${source.last_safe_result.imported} imported · ${source.last_safe_result.quarantined} held`:"No collection run yet"}</span></div><p className="break-all text-xs text-surface-400">{source.base_url} · every {formatInterval(source.collection_interval_minutes)} · last {source.last_collection_at||"never"} · next {source.next_due_at||"not scheduled"}</p><p className="text-xs text-surface-400">Health: {source.last_failure_category||"no recent error"}</p><details><summary className="cursor-pointer text-sm text-cyan-200">Permission, retention and collection details</summary><div className="mt-3 space-y-2"><p className={`text-xs ${source.permission_expires_at&&Date.parse(source.permission_expires_at)<=(now??0)?"text-rose-300":"text-surface-400"}`}>Permission {source.permission_expires_at?`expires ${source.permission_expires_at}${Date.parse(source.permission_expires_at)<=(now??0)?" (expired)":""}`:"has no recorded expiry"}</p><p className="text-xs text-surface-400">Last success {source.last_success_at||"never"} · failure {source.last_failure_category||"none"}</p><p className="text-xs">Last safe result: {source.last_safe_result?`${source.last_safe_result.status} · ${source.last_safe_result.discovered} discovered / ${source.last_safe_result.imported} imported / ${source.last_safe_result.quarantined} quarantined${source.last_safe_result.errorCategory?` · ${source.last_safe_result.errorCategory}`:""}`:"no collection result"}</p><p className="text-xs">Storage: full text {source.full_text_storage?"permitted":"blocked"} · derived data {source.derived_facts_storage?"permitted":"blocked"} · model processing {source.model_processing_allowed?"permitted":"blocked"} · raw retention {formatRetention(source.raw_retention_seconds)}</p><p className="break-all text-xs">Permission basis: {source.permission_basis}. Evidence: {source.permission_evidence}</p><p className="break-all text-xs">Permission evidence hash: {source.permission_evidence_hash||"unavailable"}</p></div></details><div className="flex flex-wrap gap-2">
    {source.state!=="enabled"&&<button disabled={busy||!!source.withdrawn_at||source.permission_reviewed_hash!==source.permission_evidence_hash} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/enable`),"Source enabled.")} className="rounded border border-emerald-300/40 px-3 py-2 text-sm disabled:opacity-40">Enable</button>}
    {source.state==="enabled"&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/disable`),"Source disabled.")} className="rounded border border-white/20 px-3 py-2 text-sm">Disable</button>}
    <button disabled={busy||source.state!=="enabled"||!source.full_text_storage} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/collect`),"Collection queued through the durable operation runtime.")} className="rounded bg-cyan-900 px-3 py-2 text-sm disabled:opacity-40">Collect now</button>
    <button disabled={busy||!!source.withdrawn_at} onClick={()=>edit(source)} className="rounded border border-white/20 px-3 py-2 text-sm disabled:opacity-40">Edit source</button>
    <details className="self-center"><summary className="cursor-pointer px-2 py-1 text-sm text-surface-400">More actions</summary><div className="mt-2 flex flex-wrap gap-2">{source.permission_evidence_hash&&source.permission_reviewed_hash!==source.permission_evidence_hash&&<button disabled={busy} onClick={()=>void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/permission-review`,{expectedHash:source.permission_evidence_hash}),"Permission review recorded for this exact evidence hash.")} className="rounded border border-amber-300/40 px-3 py-2 text-sm">Record permission review</button>}<button disabled={busy} onClick={()=>void onHistory(source.id)} className="rounded border border-white/20 px-3 py-2 text-sm">Collection history</button>{!source.withdrawn_at&&<button disabled={busy} onClick={()=>{const reason=window.prompt("Withdrawal reason");if(reason?.trim())void act(()=>apiClient.post(`/content-intelligence/sources/${source.id}/withdraw`,{reason}),"Source withdrawn and current content removed from future eligibility.");}} className="rounded border border-rose-300/40 px-3 py-2 text-sm">Withdraw</button>}</div></details>
  </div></article></SourceRowErrorBoundary>)}{!sources.length&&<div className="rounded-xl border border-white/10 p-5"><h2 className="font-semibold">No sources are connected</h2><p className="mt-1 text-sm text-surface-400">Aptlyra does not search the web automatically. Register a source only when its owner has granted permission; it starts disabled until a reviewer checks that permission.</p></div>}</div></div>;
}

function formatRetention(seconds:number){if(seconds===0)return "no raw retention";if(seconds%86400===0)return `${seconds/86400} ${seconds===86400?"day":"days"}`;if(seconds%3600===0)return `${seconds/3600} ${seconds===3600?"hour":"hours"}`;return `${Math.round(seconds/60)} minutes`;}
function formatInterval(minutes:number){if(minutes%1440===0)return `${minutes/1440} ${minutes===1440?"day":"days"}`;if(minutes%60===0)return `${minutes/60} ${minutes===60?"hour":"hours"}`;return `${minutes} minutes`;}
